### ISSUE TITLE
neocomplete error 

### ISSUE THREAD

**Issue by vakosel** [rafi/vim-config#1]
Hi and well done  for your efforts !
i get the following error when i start typing after a fresh install 

Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>126_check_fallback:
line    3:
E121: Undefined variable: neocomplete
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>126_check_fallback:
line    3:
E15: Invalid expression: empty(g:neocomplete#fallback_mappings) && len(matchstr(cur_text, '\h\w*$'))   >= g:neocomplete#auto_completion_start_length && !neocomplete.skip_next_complete && !neocomplete#complete#_check_previous_position(      cur_text, complete_pos)
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>126_check_fallback:
line    3:
E121: Undefined variable: neocomplete
Error detected while processing function neocomplete#handler#_do_auto_complete..<SNR>126_check_fallback:
line    3:
E15: Invalid expression: empty(g:neocomplete#fallback_mappings) && len(matchstr(cur_text, '\h\w*$'))   >= g:neocomplete#auto_completion_start_length && !neocomplete.skip_next_complete && !neocomplete#complete#_check_previous_position(      cur_text, complete_pos)
... the list is not ended.. 
All have to do with neocomplete.. 

Any idea?

**Comment by rafi** [comment]
The plugin author of neocomplete has just issued a fix for this, see [Shougo/neocomplete.vim:16af9081](https://github.com/Shougo/neocomplete.vim/commit/16af908181ab4f7c31a5eca4b5506cd4413766ba). Update your plugin installation.
