### ISSUE TITLE
Vim(for):E714: List required

### ISSUE THREAD

**Issue by mm1ke** [rafi/vim-config#100]
Hi,

I've updated my neovim config today and now i'm getting following error on starting nvim:

```
Error detected while processing /home/ai/.config/nvim/config/vimrc:
line  137:
Vim(for):E714: List required
Press ENTER or type command to continue
```

**Comment by rafi** [comment]
Please update your plugins with dein: `:call dein#check_update()`

**Comment by mm1ke** [comment]
Hi,

I actually found the culprint of my problem. FYI, my plugins were already up-to-date. However, since you recently added the rust.vim configuration i've disabled (commented out) it in my ```loclal.plugins.yaml``` file - which is was then empty and produces this error.
I've simply removed this file and now it works again. Maybe you could check for this somehow because it was really not that obvious.
