### ISSUE TITLE
Support django syntax template

### ISSUE THREAD

**Issue by trprado** [rafi/vim-config#101]
If possible add Django syntax template, this link has more information https://code.djangoproject.com/wiki/UsingVimWithDjango

**Comment by rafi** [comment]
I use Python, but never Django. Can you give me some links to django actual code files I could test configuration with?

**Comment by trprado** [comment]
In this link, you will find the code samples https://github.com/realpython/materials/tree/4dd5d79634efbffeb8999052a9e94b3dba4b25ba/rp-portfolio or, if you like, in this other link you will find a django tutorial used to create the samples of first link https://realpython.com/get-started-with-django-1/

**Comment by rafi** [comment]
@trprado Could you be a little more specific about the exact file that you wise to be highlighted and what are you expecting?
