### ISSUE TITLE
how to use whitespace.vim?

### ISSUE THREAD

**Issue by taigacute** [rafi/vim-config#102]
i found `whitespace.vim` is a plugin which to remvoe  the space end of line by `WhitespaceErase`， but i also found this
```
" Remove spaces at the end of lines
nnoremap <silent> ,<Space> :<C-u>silent! keeppatterns %substitute/\s\+$//e<CR>
```
so what is the different between the  `whitespace.vim` and `, <Space>`

**Comment by rafi** [comment]
Hi @taigacute, the <kbd>,</kbd>+<kbd>Space</kbd> is a simple mapping to erase trailing whitespace. The plugin `whitespace.vim` sets the same behavior with a `WhitespaceErase` command, but more importantly in **normal** mode it finds non-consistent leading whitespace (tabs & spaces mixed together) and highlights them. It hides highlighting in insert mode for convenience. I need to clean it up a little bit :)

**Comment by taigacute** [comment]
Hi @rafi My configuration uses some of your core code and didn't get your consent, but I have mentioned your thanks in the README, I don't know do  you mind i do this
