### ISSUE TITLE
MRU & pluginList giving errors in vim 8.1/neovim

### ISSUE THREAD

**Issue by kschulz-samsung** [rafi/vim-config#104]
When I try to use the MRU function in the side menu, I get the following error: 

Executing:  Denite file_old
[denite] Traceback (most recent call last):
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/rplugin.py", line 26, in start
[denite]     return ui.start(args[0], context)
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 63, in start
[denite]     self._start_sources_queue(context)
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 144, in _start_sources_queue
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 187, in _start
[denite]     self._init_denite()
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/ui/default.py", line 682, in _init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 35, in on_init
[denite]     self._put('on_init', [context])
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/parent.py", line 62, in _put
[denite]     return self._child.main(name, args, queue_id=None)
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 69, in main
[denite]     self.on_init(args[0])
[denite]   File "/home/kschulz/.cache/vim/dein/repos/github.com/Shougo/denite.nvim/rplugin/python3/denite/child.py", line 133, in on_init
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "file_old" is not found.
[denite] Please execute :messages command.
Press ENTER or type command to continue

**Comment by kschulz-samsung** [comment]
could look like the denite commands have been changed. file_old is not file/old and --no-quit has been removed.

**Comment by rafi** [comment]
Hi, yes, Denite had some changes. It should be `:Denite file/old` now, I fixed it, thanks.
