### ISSUE TITLE
tab part unrecognized symbols

### ISSUE THREAD

**Issue by sdxy36** [rafi/vim-config#105]
![2019-06-27 18-41-30屏幕截图](https://user-images.githubusercontent.com/11732890/60260165-75b50b80-990b-11e9-9834-bb172ba1c6a2.png)
ubuntu18.04(default terminal) and macos(iTerm2) all the same problem. what step did I miss

**Comment by rafi** [comment]
These are just ascii block characters.. nothing fancy :) create your own theme in `themes/`.
