### ISSUE TITLE
Color problem on tab and status line

### ISSUE THREAD

**Issue by yikkai95** [rafi/vim-config#106]
As seen in the screenshot, the color is inconsistent in the status line. Anything I can do for it?

![Screenshot 2019-07-11 at 10 13 48 AM](https://user-images.githubusercontent.com/30519030/61017143-b52c2f00-a3c4-11e9-9c99-f1f13840c3ba.png)

**Comment by sdxy36** [comment]
Have you solved it? I have the same problem.

**Comment by rafi** [comment]
I committed many changes, you can now disable the statusline and use a different one.
