### ISSUE TITLE
tab and status problem

### ISSUE THREAD

**Issue by sdxy36** [rafi/vim-config#107]
![2019-07-15 04-11-36屏幕截图](https://user-images.githubusercontent.com/11732890/61188776-b86e3600-a6b6-11e9-9386-fd1c4bc8082f.png)
![2019-07-15 04-11-54屏幕截图](https://user-images.githubusercontent.com/11732890/61188777-b906cc80-a6b6-11e9-80e8-68e9b6e18746.png)

why?

**Comment by rafi** [comment]
I'm not sure about the question, these are just playful normal ascii characters. You can disable statusline and add yours.
