### ISSUE TITLE
Modified this configuration file but it does not take effect

### ISSUE THREAD

**Issue by MaxJohnXiang** [rafi/vim-config#108]
i try to change nerdtree.vim , but dose not work. 

let g:NERDTreeWinSize = 100

the nerdtree window is same size as before. 

let g:NERDTreeQuitOnOpen = 0

the nerdtree still auto close on open .

How do i change the nerdtree config , make it's work properly

**Comment by rafi** [comment]
I have removed NERDTree in-favour of [Defx](https://github.com/shougo/defx.nvim).

To your questions, checkout `config/plugins/nerdtree.vim` - there are custom behaviors there you can change.
