### ISSUE TITLE
Defx icon missing on neovim.

### ISSUE THREAD

**Issue by Zheaoli** [rafi/vim-config#109]
![image](https://user-images.githubusercontent.com/7054676/61211161-64546780-a731-11e9-9c36-456e5ae1d956.png)

When I use the newest config for nvim, I find that defx shows incorrectly. It seems like missing some icons or fonts.

![image](https://user-images.githubusercontent.com/7054676/61211254-b5645b80-a731-11e9-875d-a37edde4816b.png)

![image](https://user-images.githubusercontent.com/7054676/61211277-c4e3a480-a731-11e9-942f-0f26ad97fac3.png)

**Comment by sdxy36** [comment]
Maybe you need to use nerdfont

**Comment by Zheaoli** [comment]
@sdxy36 nerdfont?

**Comment by sdxy36** [comment]
> @sdxy36 nerdfont?

like this:
<img width="525" alt="WX20190717-012648@2x" src="https://user-images.githubusercontent.com/11732890/61315736-022f5b80-a832-11e9-99f8-88cce620bce0.png">

https://github.com/ryanoasis/nerd-fonts

**Comment by sdxy36** [comment]
> @sdxy36 nerdfont?
like this:
![image](https://user-images.githubusercontent.com/11732890/61315853-44589d00-a832-11e9-9931-17af14dbf268.png)
https://github.com/ryanoasis/nerd-fonts

**Comment by thecontinium** [comment]
`brew cask install font-hack-nerd-font`

**Comment by Zheaoli** [comment]
@sdxy36 @thecontinium thanks a lot. I solve this problem

**Comment by rafi** [comment]
See https://www.nerdfonts.com/

**Comment by PegasusWang** [comment]
Add `brew cask install font-hack-nerd-font` to readme.md ?  @rafi

**Comment by rafi** [comment]
good idea @PegasusWang, what's the difference between the `-mono` variants? `font-hack-nerd-font` vs. `font-hack-nerd-font-mono`?
