### ISSUE TITLE
some plugin breaks ysiw" key-binding

### ISSUE THREAD

**Issue by kimusan** [rafi/vim-config#110]
Hi,
if I start a clean gvim with your config then the classic ysiw" key combo for surrounding a word with quotes ("") works. But as soon as I open an existing file - e.g. a c-code file, then it does not work anymore. It seems like the "i" is interpreted as "insert and show completion list popup.

Do you know if there is a way to fix this?

**Comment by rafi** [comment]
Hi @kimusan, you are referring to the plugin [vim-surround](https://github.com/tpope/vim-surround), it is not included in my vim-config, I use different plugins. Did you add this plugin yourself?

**Comment by rafi** [comment]
You can add your custom plugins in `config/local.plugins.yaml`.

**Comment by yusiwen** [comment]
> Hi @kimusan, you are referring to the plugin [vim-surround](https://github.com/tpope/vim-surround), it is not included in my vim-config, I use different plugins. Did you add this plugin yourself?

Hi @rafi,  and which plugin do you use for this function like 'vim-surround' provided? The README is too long, and I can't find any information about it. 

Thx

**Comment by rafi** [comment]
I use [vim-sandwich](https://github.com/machakann/vim-sandwich)

**Comment by yusiwen** [comment]
@rafi  Got it, thx!
