### ISSUE TITLE
Invalid plugins.yaml

### ISSUE THREAD

**Issue by throwawaymd** [rafi/vim-config#114]
Hi,
The file https://github.com/rafi/vim-config/blob/master/config/plugins.yaml is not a valid yaml file. 
The error is on line n°16: https://github.com/rafi/vim-config/blob/master/config/plugins.yaml#L16

( the character ":" cannot be used directly, since it is a yaml special char )

Maybe it should be replaced with
```yaml
- { repo: tpope/vim-sleuth, hook_add: "let g:sleuth_neighbor_limit = 5" }
```

**Comment by rafi** [comment]
Hi, thanks for the information. I fixed it in the latest commit. Check out [yq](https://github.com/mikefarah/yq) for better YAML parsing.
