### ISSUE TITLE
load tmux related plugins only for linux/mac but not windows/dos

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#115]
since Dein also works on Windows rafi/vim-config also works on Windows - awesome :-)
But tmux doesn't work on Windows (except WSL). It would be great if tmux related plugins could be disabled for Windows/dos.

**Comment by rafi** [comment]
I use two plugins for Tmux integration:
1. [christoomey/vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator)
1. [wellle/tmux-complete.vim](https://github.com/wellle/tmux-complete.vim)

Do they affect Vim's behavior without Tmux?

**Comment by kraxli** [comment]
Thanks for coming back on this! Yes, completion throws an error that tmux
can not be found. I will give you more details after reenabling the plugins
on my Windows machine.

**Comment by kraxli** [comment]
it seems to be the plugin `wellle/tmux-complete.vim`  which results in the error "[deoplete] stderr from child process:b'tmux: not found'

conditioning the plugin with ` if: has('unix')` solves the problem (what I also did for `vim-tmux-navigator)`

**Comment by rafi** [comment]
Thanks @kraxli, check my latest commit (5218f7f) with appropriate Windows detection. Let me know if it works for you.

**Comment by kraxli** [comment]
Many thanks!! Seems to working well :-)
