### ISSUE TITLE
Still not working well on Debian with homebrew

### ISSUE THREAD

**Issue by andrius** [rafi/vim-config#116]
I just made a try and still getting errors with neovim. Host machine: Debian 9.7 with homebrew installed

Case 1 

```
brew install neovim
# installing vim-config
```

When I starting vim and trying to edit files, I get this:
```
                                Error detected while processing /home/ak/.cache/vim/dein/repos/github.com/ncm2/float-preview.nvim/plugin/float_preview.vim:
line   14:
E216: No such group or event: CompleteChanged * call float_preview#_menu_popup_changed()
Press ENTER or type command to continue
```

Case 2

```brew unlink neovim
brew install --HEAD neovim
# reinstalling vim-config
```

No errors, but any popus does not working, ctags etc too. Just getting fancy looking nvim

**Comment by rafi** [comment]
Hi @andrius, thanks for the report. My latest commit 41d166a checks if `CompleteChanged` event exists (supported only on nvim nightly and vim v8.1.1138), should fix this issue. Let me know!

**Comment by andrius** [comment]
Works, but now I had to do `make upgrade` and `make update` and few times `:UpdateRemotePlugins`. But it worth so, nvim looks fantastic! Thank you!

**Comment by rafi** [comment]
- Don't use `:UpdateRemotePlugins`, it ignores lazy-loaded plugins (via dein), so you better run: `:call dein#remote_plugins()` which will take into account the lazy ones.
- Reading the YAML files happens only once after they change. If you want to delete this cached state, run: `:call dein#clear_state()` and after the next you start n/vim, the state will rebuild.
- If you make a lot of modifications to your `local.plugins.yaml`, you'll eventually need to run `:call dein#recache_runtimepath()` for dein to re-merge all the plugin essentials. Run it with a fresh state.

See #117 for a new feature to disable or overwrite plugin configurations.

Let me know if you're cool.
