### ISSUE TITLE
Better way of disabling/reconfiguring a plugin

### ISSUE THREAD

**Issue by ialiendeg** [rafi/vim-config#117]
Hi Rafi, first of all, congratulations for this project, I use it every day and I'm a happier developer since I knew of it :)

But I have a proposal for an enhancement. Since some time ago, I've been disabling some of your plugins by simply commenting out some lines in plugins.yaml file, but the merging of your new changes is getting more difficult every time, so I started to investigate the way you load the plugins and ended with a solution I think is, at least, good to discuss.

Keep in mind that I'm not a vim script developer (and specially I have not much dein manager knowledge), so in the code, there is a commented out solution that I think is the best, but somehow it's not working. It would permit us to merge our local configuration with yours, and disable plugins simply adding an `if: 0` condition.

At this moment, I have a momentary solution that consists in adding a 'disable' key in the local.plugin.yaml file (it's working for me, but I'd prefer the other solution, maybe you know how to do it the right way).

The code patch is this (note the debug messages, I'd expect the plugin data second message, after calling the dein#config, to have changed with the local one, but it's not):
```
diff --git a/autoload/etc/providers/dein.vim b/autoload/etc/providers/dein.vim
index bc05754..ff91fe3 100644
--- a/autoload/etc/providers/dein.vim
+++ b/autoload/etc/providers/dein.vim
@@ -41,7 +41,23 @@ function! etc#providers#dein#_init(config_paths) abort
 		" Start propagating file paths and plugin presets
 		call dein#begin(l:cache_path, extend([expand('<sfile>')], a:config_paths))
 		for plugin in l:rc
-			call dein#add(plugin['repo'], extend(plugin, {}, 'keep'))
+			let l:plugin_name = split(plugin['repo'], '/')[-1]
+			" FIXME: This should be the right solution, so we can merge the local plugins configuration, but it's not working
+			" echomsg 'plugin_name -------------------------------------' l:plugin_name
+			" if dein#get(l:plugin_name) != {}
+			" 	echomsg 'plugin_cfg ------------' string(plugin)
+			" 	echomsg 'plugin_data ------------ 1' string(dein#get(l:plugin_name))
+			" 	call dein#config(l:plugin_name, extend(plugin, {}, 'keep'))
+			" 	echomsg 'plugin_data ------------ 2' string(dein#get(l:plugin_name))
+			" else
+			" 	call dein#add(plugin['repo'], extend(plugin, {}, 'keep'))
+			" endif
+			" NOTE: We use 'disable' key in local.plugins.yaml file to disable a plugin completely while the above solution is broken
+			if has_key(plugin, 'disable')
+				call dein#disable(l:plugin_name)
+			else
+				call dein#add(plugin['repo'], extend(plugin, {}, 'keep'))
+			endif
 		endfor
 
 		" Add any local ./dev plugins
```

Another solution could be to substitute the configuration for a repo at the moment of sourcing the yaml files, so only one of them is used at the moment of calling dein#add, but I found this more difficult to implement (this solution is a merge of plugins.yaml with local.plugins.yaml).

Tell me if you think this is not necessary, I know there have been only a couple of questions about disabling plugins so far, but I think it's a good improvement.

**Comment by rafi** [comment]
Hi @ialiendeg, I'm glad you find this setup helpful! I love tweaking my editor.

I've been thinking about the issue of disabling and changing the plugins in `plugins.yaml` in the past few days. I only use this file, and not `local.plugin.yaml`, so I appreciate your input about this perspective. I'll think about this and experiment with a few ideas I have.

Can you share your `local.plugin.yaml` and modifications so I could get an idea about your requirements?

**Comment by ialiendeg** [comment]
Sure. At this moment, the relevant lines of my local plugins file are these (the commented ones are those I wanted to use initially):
```
---
- repo: benekastah/neomake
  disable: 0
  # if: 0
- repo: Shougo/denite.nvim
  disable: 0
  # if: 0
```

**Comment by ialiendeg** [comment]
Just a little help.

I did a couple more tests but I think dein is not able to process two calls to dein#add for the same repo, neither a second call to dein#config for an already added repo. I suppose this because of https://github.com/Shougo/dein.vim/blob/1ef8bf025ea905ffeef774c08e7143c48355d881/autoload/dein/util.vim#L486 (I checked that the plugin is already included in there at the second call).

Given this, I suppose the right way would be to merge the configs from plugins.yaml and local.plugins.yaml.

**Comment by ialiendeg** [comment]
Nice, thx! :)

**Comment by rafi** [comment]
Can you try pulling latest commit and test? I added a dedupe function, it overwrites newer definitions from local user config yamls, and among things allows to disable a plugin with `if: 0`. It doesn't really affect the startup speed, and happens only when you change those yamls.

You will need to run `:call dein#clear_state()` and `:call dein#recache_runtimepath()` probably for certain plugins that dein merges.

Let me know if it works for you! I thought about grouping with shallow merge, turning the yaml into a dict, not a list, e.g.:

```yaml
plugins:
- repo: a
- ...
denite:
- ...
neomake:
- ...
```

and being able to overwrite by provising an empty key, e.g. `denite: []`...

**Comment by ialiendeg** [comment]
Checked, for me it's working.
