### ISSUE TITLE
neovim :terminal color issue

### ISSUE THREAD

**Issue by cj** [rafi/vim-config#121]
I'm having an issue using `:terminal` inside Nvim, the colors on the left are inside Nvim (which display the wrong color) but the colors on the right are directly in the terminal (which are the correct ones):

![](https://cl.ly/3af073f5050d/Image%2525202019-08-27%252520at%2525209.53.30%252520pm.png)

iTerm2: Build 3.3.2

<details>
<summary>
nvim -v
</summary>
NVIM v0.4.0-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190821-50970-a05tb7/build/config -I/tmp/neovim-20190821-50970-a05tb7/src -I/usr/local/include -I/tmp/neovim-20190821-50970-a05tb7/deps-build/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190821-50970-a05tb7/build/src/nvim/auto -I/tmp/neovim-20190821-50970-a05tb7/build/include
Compiled by cj@cj-osx.tx.rr.com

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-86c182c/share/nvim"

</details>

<details>
<summary>
Healthcheck results:
</summary>

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: macOS-clipboard

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/local/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/local/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Users/cj/.cache/vim/venv/neovim3/bin/python"
  - INFO: Executable: /Users/cj/.cache/vim/venv/neovim3/bin/python
  - INFO: Python version: 3.7.4
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]
  - INFO: Host: /Users/cj/.rbenv/shims/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v10.16.2
  - INFO: Neovim node.js host: /Users/cj/.local/lib/node/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
</details>

I'm using all the settings from https://github.com/rafi/.config and the terminal color scheme from https://github.com/rafi/.config/blob/master/termite/config

**Comment by rafi** [comment]
I don't use termite anymore, I use [alacritty](https://github.com/jwilm/alacritty) with [this theme](https://github.com/rafi/.config/blob/master/alacritty/alacritty.yml#L48-L66).

Also, I don't use the `:terminal` feature in neovim at all, I use tmux, always. And so, I have not configured anything related to the terminal. You can read about its configuration with `:h terminal-configuration`

**Comment by cj** [comment]
@rafi thank you for the response.  I don't use `:terminal` either, but vim-test uses it if I'm running a quick inline test.

```
- repo: janko-m/vim-test
  on_cmd: [TestLast, TestNearest, TestLast]
  hook_add: |
    map <silent>T :TestNearest<cr>
    map <silent><C-t> :TestLast<cr>
    map <silent><leader>T :TestFile<cr>

    let g:test#strategy = "neovim"
    let g:test#preserve_screen = 1
    let g:test#javascript#jest#executable = 'NODE_OPTIONS="-r esm" jest'
    let g:test#ruby#bundle_exec = 1
    let g:test#ruby#patterns = {
      \ 'test': [
        \ '\v^\s*def (test_\w+)',
        \ '\v^\s*it%(\(| )%("|'')(.*)%("|'')',
        \ '\v^\s*test%(\(| )%("|'')(.*)%("|'')',
        \],
      \ 'namespace': [
        \ '\v^\s*%(class|module) (\S+)',
        \ '\v^\s*describe%(\(| )%("|'')(.*)%("|'')',
        \ '\v^\s*describe%(\(| )(\S+)',
        \],
        \}
```

I'll take a look and see if I can fix it!

Cheers!

**Comment by cj** [comment]
For anyone else using vim-test you just need to add this to your local.vim:

```
let g:terminal_color_0 = '#2a2a2a'
let g:terminal_color_1 = '#d370a3'
let g:terminal_color_2 = '#6d9e3f'
let g:terminal_color_3 = '#b58858'
let g:terminal_color_4 = '#6095c5'
let g:terminal_color_5 = '#ac7bde'
let g:terminal_color_6 = '#3ba275'
let g:terminal_color_7 = '#ffffff'
let g:terminal_color_8 = '#686868'
let g:terminal_color_9 = '#ffa7da'
let g:terminal_color_10 = '#a3d572'
let g:terminal_color_11 = '#efbd8b'
let g:terminal_color_12 = '#98cbfe'
let g:terminal_color_13 = '#e5b0ff'
let g:terminal_color_14 = '#75daa9'
let g:terminal_color_15 = '#cfcfcf'
```

**Comment by thecontinium** [comment]
If anyone wants to use the :terminal command these mappings work for me:

" terminal mappings
" map jj to exit terminal-mode
:tnoremap jj <C-\><C-N>
" use `CTRL+{h,j,k,l}` to navigate windows from any mode
:tnoremap <C-h> <C-\><C-N><C-w>h
:tnoremap <C-j> <C-\><C-N><C-w>j
:tnoremap <C-k> <C-\><C-N><C-w>k
:tnoremap <C-l> <C-\><C-N><C-w>l
:inoremap <C-h> <C-\><C-N><C-w>h
:inoremap <C-j> <C-\><C-N><C-w>j
:inoremap <C-k> <C-\><C-N><C-w>k
:inoremap <C-l> <C-\><C-N><C-w>l
:nnoremap <C-h> <C-w>h
:nnoremap <C-j> <C-w>j
:nnoremap <C-k> <C-w>k
:nnoremap <C-l> <C-w>l

**Comment by rafi** [comment]
@cj & @thecontinium thanks for the feedback
