### ISSUE TITLE
vim-hexokinase install error

### ISSUE THREAD

**Issue by sdxy36** [rafi/vim-config#122]
`[dein] Failed to clone 'hexokinase'. Retry scheduled
[dein] Cloning into '/home/laoqin/.cache/vim/dein/repos/github.com/RRethy/vim-hexokinase/hexokinase'...Cloning into '/home/laoqin/.cache/vim/dein/repos/github.com/RRethy/vim-hexokinase'...
[dein] Submodule 'hexokinase' (git@github.com:RRethy/hexokinase.git) registered for path 'hexokinase'
[dein] Cloning into '/home/laoqin/.cache/vim/dein/repos/github.com/RRethy/vim-hexokinase/hexokinase'...
[dein] ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory^M
[dein] Host key verification failed.^M
[dein] fatal: Could not read from remote repository.
[dein] Please make sure you have the correct access rights
`
...
`[dein] Updated plugins:
[dein]   vim-pug(1 change)
[dein]   thesaurus_query.vim(1 change)
[dein] Error installing plugins:
[dein]   vim-hexokinase
`

**Comment by rafi** [comment]
@sdxy36 thanks for the repo. can you disable the `build: make hexokinase` in `config/plugins.yaml` and remove the plugin with: `rm -rf ~/.cache/vim/dein/repos/github.com/RRethy` and rerun nvim?

**Comment by rafi** [comment]
It looks like you have a problem with authentication to GitHub
> ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory

**Comment by Manikanta-Sangu** [comment]
@sdxy36 I got similar error when I didn't setup ssh with my GitHub. Once done, it resolved the issue.

**Comment by sdxy36** [comment]
> @sdxy36 I got similar error when I didn't setup ssh with my GitHub. Once done, it resolved the issue.

[Force](https://gist.github.com/taoyuan/bfa3ff87e4b5611b5cbe) git to use https:// instead of git://

`git config --global url."https://github.com/".insteadOf git@github.com:`
`git config --global url."https://".insteadOf git://`

it resolved.
