### ISSUE TITLE
Latest Changes : Errors on clean install

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#126]
After the latest changes I get many errors from a clean install.  
I removed both the cache and .local/share/nvim. 

These are the errors at the end of the install ...

[dein] Error occurred while executing hook: defx.nvim
[dein] Vim(source):E484: Cannot open file /config/plugins/defx.vim
[dein] Error occurred while executing hook: deoplete.nvim
[dein] Vim(source):E484: Cannot open file /config/plugins/deoplete.vim
[dein] Error occurred while executing hook: denite.nvim
[dein] Vim(source):E484: Cannot open file /config/plugins/denite.vim
[dein] Error occurred while executing hook: goyo.vim
[dein] Vim(source):E484: Cannot open file /config/plugins/goyo.vim
[dein] Error occurred while executing hook: neomake
[dein] Vim(source):E484: Cannot open file /config/plugins/neomake.vim
[dein] Vim(call):E739: Cannot create directory /tags: permission denied
[dein] /Users/thecontinium/.cache/vim/dein/repos/github.com/ludovicchabant/vim-gutentags/plugin/gutentags.vim, line 77
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
not found in 'packpath': "pack/*/start/*"
Reading ShaDa file "/Users/thecontinium/.local/share/nvim/shada/main.shada" info marks oldfiles FAILED
Writing ShaDa file "/Users/thecontinium/.local/share/nvim/shada/main.shada"

**Comment by thecontinium** [comment]
Looks like the environment variable $VIM_PATH and $DATA_PATH are not getting resolved.

**Comment by thecontinium** [comment]
Adding:

let $VIM_PATH = fnamemodify(resolve(expand('<sfile>:p')), ':h:h')
let $DATA_PATH = expand(($XDG_CACHE_HOME ? $XDG_CACHE_HOME : '~/.cache').'/vim')
if has('nvim') && isdirectory($DATA_PATH . '/venv/neovim3')
       let g:python3_host_prog = $DATA_PATH . '/venv/neovim3/bin/python'
endif

to the top of `config/init.vim` is a **temp** fix for most of the issues.

I am still getting not found in 'pack path' and some ShaDa file errors.

**Comment by rafi** [comment]
Hi @thecontinium, can you check with latest commit d8d8e07 ? The `&packpath` warnings aren't errors. I'll see what I can do.

Also, dein seems to load all plugins with `on_path: .*` suddently on VimEnter. I need to open an issue at dein.

**Comment by thecontinium** [comment]
Hi

Thanks for the update.

Mostly looks good apart from

1. `make uninstall && make install` results in not having a python environment and:
```
[dein] (135/138) [+++++++++++++++++++-] vim-altr
[dein] Error occurred while executing hook: neomake
[dein] Vim(if):E121: Undefined variable: g:python3_host_prog
[dein] Done: (2019/09/19 12:47:29)not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
```
Can you call `venv.sh ` if the python envonment is not there on an install ?
Maybe add a reinstall directive to `make uninstall && ./venv.sh && make install`

2. I have a local config yaml that has an entry: 

```
- repo: Olical/conjure
  rep: v1.*.*
  build: bin/compile
  on_ft: clojure
```

This worked before but now results in a dein error and stops the install with this error:

`[dein] Done: (2019/09/19 12:48:25)not found in 'runtimepath': "autoload/conjure.vim"`

Suspect this may be a dein issue; what do you think ?

3. make uninstall && ./venv.sh && make install without my local config's is good apart from these pack path messages:  

```
[dein] (127/137) [++++++++++++++++++--] python_match.vim
[dein] (133/137) [+++++++++++++++++++-] vim-denite-session
[dein] Done: (2019/09/19 13:03:28)not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
not found in 'packpath': "pack/*/start/*"
[dein] Update started: (2019/09/19 13:03:28)
```

**Comment by wangjinjie722** [comment]
Got the same issue

**Comment by 20jam** [comment]
Got the same issue

**Comment by rafi** [comment]
As far as I can see, there are any errors anymore, except the `packpath` warnings, which is OK, because I don't use vim8 package feature.

@20jam @wangjinjie722 @thecontinium can you see any other errors?

**Comment by thecontinium** [comment]
looks good to me - thx
