### ISSUE TITLE
copy paste block of code

### ISSUE THREAD

**Issue by dzirg44** [rafi/vim-config#128]
hello guys! Thank you for your work! I have  maybe  a stupid  question about copying and pasting.
I have tried to do this as usual (select code with `V`, and `yy`) but it doesn't work . Could somebody help me?

**Comment by rafi** [comment]
Hi @dzirg44 - what operating system are you using? nvim or vim? what version? Have all the plugins been installed correctly?

Trying running:
`:call dein#update()`
If it's successful (hit `:message` to see), run:
`:call dein#recache_runtimepath()`
Restart n/vim and try again.

**Comment by dzirg44** [comment]
OS
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
```
vim 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov  6 2019 08:27:54)
macOS version
Included patches: 1-2250
Compiled by Homebrew
```
`:call dein#update()` - completed without any errors.

![1](https://user-images.githubusercontent.com/16103834/68371320-25667980-0147-11ea-9cfe-2fa14d058d2b.gif)

  I can  copy 2 lines ( with pushing `y` once and arrows ) but for 3 and more it doesn't work, because selected area disappears.

**Comment by rafi** [comment]
@dzirg44 can you try replacing the clipboard setting in `config/general.vim` with this and try again?

```vim
	set clipboard& clipboard^=unnamed,unnamedplus
```
