### ISSUE TITLE
How did you make those tables related to plugins and commands?

### ISSUE THREAD

**Issue by thepenguinthatwants** [rafi/vim-config#129]
For example I noticed you had such nice tables done but I am unsure how its done.

Do you just manually write it or are you using some plugins to make it look like that?

| name                         | description                                              |
| ---------------------------- | -------------------------------------------------------- |
| [shougo/defx.nvim]           | dark powered file explorer implementation                |
|

**Comment by rafi** [comment]
Use Markdown table annotations and link anchors:

```
| Name           | Description
| -------------- | ----------------------
| [somelink] | Some text

[somelink]: https://github.com
```
