### ISSUE TITLE
Unknown function: ColorSchemeTheme

### ISSUE THREAD

**Issue by lobida** [rafi/vim-config#13]
Hello Sir,
I installed latest vim-config following your steps, and run vim in terminal
there's some errors here:
Error detected while processing ColorScheme Auto commands for "*":
E117: Unknown function: ColorSchemeTheme

Could you help? 
Thanks

**Comment by rafi** [comment]
Hello, could you please try installing again? Many new changes were introduced.

**Comment by rafi** [comment]
This should be fixed with latest updates.
