### ISSUE TITLE
Unknown function: _denite_init

### ISSUE THREAD

**Issue by macintacos** [rafi/vim-config#131]
Clean install on macOS Catalina 10.15.1, using NVIM v0.4.3. I get the following error almost always when calling one of the functions related to Denite:

```
[denite] Vim(call):E117: Unknown function: _denite_init
[denite] function denite#helper#call_denite[7]..denite#start[4]..<SNR>125_start[1]..denite#initialize[1]..denite#init#_initialize, line 33
[denite] denite failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
```

I basically _just now_ git clone'd this setup and ran `make install`, so it's not like I've made any modifications to get this to work. Any ideas what's going on? It breaks a lot of the setup. I got that error when calling `; + f` (which should be file search; I say "should" because I've never actually gotten it to work 🙂)

**Comment by rafi** [comment]
Hi. Can you try running `:call dein#remote_plugins()` and restart nvim to see if it works?

**Comment by macintacos** [comment]
@rafi it does not fix it, same error shows up.

**Comment by lifala71** [comment]
hi,
i have a similar error

`[defx] Vim(call):E117: Fonction inconnue : _defx_init
[defx] function defx#util#call_defx[2]..defx#start[1]..defx#initialize[1]..defx#init#_initialize[5]..defx#init#_channel, ligne 26                                                                    
Erreur détectée en traitant function defx#util#call_defx[2]..defx#start[1]..defx#initialize[1]..defx#init#_initialize[5]..defx#init#_channel[32]..defx#init#_python_version_check :
ligne    9 :
E121: Undefined variable: g:defx#_python_version_check
E15: Expression invalide : g:defx#_python_version_check
`

**Comment by rafi** [comment]
I'm not able to reproduce this, but looks like a python issue. Make sure you have python 3 installed. Python 2 is officially DEAD.

**Comment by macintacos** [comment]
I’ve moved on to use SpaceVim, so I’ll just close this. Note: my error message had nothing to do with Python (I have Python3 installed just fine).

**Comment by FSCYT** [comment]
```
[defx] Vim(call):E117: Unknown function: _defx_init
[defx] function defx#util#call_defx[2]..defx#start[10]..defx#initialize[1]..defx#init#_initialize[5]..defx#init#_channel, line 26
[defx] defx failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
```

## Additional Information
**Python Version:** `3.9.9`
**NeoVim Version:** `0.6.0`
pynvim already installed
