### ISSUE TITLE
How to show error message in source code (golang)

### ISSUE THREAD

**Issue by Tenyun** [rafi/vim-config#133]
Good morning,

i'm looking for a way to display error messages marked red in the source code.

Example
```
papackage main

import (
	"fmt"
)

func main() {
	fmt.Printf("Hello, world\n")

        a := 42
        b := 43
}
```

After saving the file, the two variables a & b are marked red but the error message is not displayed anywhere. 

How can I display the error message if I move the cursor over the red marked areas?

**Comment by Tenyun** [comment]
Okay, I've found a partial solution.
Linting is done by neomake but not automatically.
In `config/plugins.yaml` I found the line `call neomake#configure#automake('rwn', 300)`.
Actually this should call neomake automatically when you read the file, write it and switch to normal mode or do I misunderstand?

**Comment by rafi** [comment]
Hi @Tenyun, you should definitely check neomake's docs. It sounds right though. I switched from neomake to ale, and pretty happy so-far, so I'll probably push new updates soon.
