### ISSUE TITLE
getting `[dein] Plugin name "fzf" is not found`

### ISSUE THREAD

**Issue by andrius** [rafi/vim-config#134]
After fresh reinstall if nvim with linuxbrew (`brew install --HEAD neovim`), I'm getting following message:

```
[dein] Plugin name "fzf" is not found
```

**Comment by PegasusWang** [comment]
try `brew install fzf`  first ?

**Comment by PegasusWang** [comment]
My MacOS can work, but centos server same issue:

https://github.com/Shougo/dein.vim/issues/74

**Comment by rafi** [comment]
@andrius the plugin relies on fzf being installed at `/usr/local/opt/fzf`, which is probably only true in macOS. I'm planning on fixing it, probably using a shallow clone to the fzf repository because it's so big.

**Comment by rafi** [comment]
This has been fixed. Added fzf shallow clone and installation:
```yaml
- repo: junegunn/fzf
  merged: 0
  on_cmd: FZF
  type__depth: 1
```
