### ISSUE TITLE
not found in 'packpath': "pack/*/start/*"

### ISSUE THREAD

**Issue by MaxJohnXiang** [rafi/vim-config#135]
~/.config/nvim master ?                                                                                                                                                                                  8.15 xiangyun@Max-MacBook-Pro ❯ make update
Already up to date.
nvim -V1 -es -i NONE -N -u config/init.vim -c "try | call dein#clear_state() | call dein#update() | finally | qall! | endtry"
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/matchit"
not found in 'packpath': "pack/*/start/*"
not found in 'runtimepath': "plugin/**/*.vim"

**Comment by sergiopatino** [comment]
getting the same error

**Comment by sergiopatino** [comment]
heads up. this is an issue with the fish shell. doesn't happen if you run make from bash or zsh.

**Comment by rafi** [comment]
these are just warnings. the new pack mechanism in Vim just looks there for plugins installed with this method, see `:h packages`

**Comment by rafi** [comment]
I've tested it in fish shell, and it works fine. Please reopen if there's an issue.

**Comment by rafi** [comment]
I've improved the Makefile and fixed the `packpath` warnings at https://github.com/rafi/vim-config/commit/b7cd3b85ea8012ce91892cb68fa5847a3a87012d
