### ISSUE TITLE
in which case use_global can be 0

### ISSUE THREAD

**Issue by Spid3** [rafi/vim-config#136]
I'm new in vim,there is the question
In vimrc file there is a func:
```
function! s:source_file(path, ...)
	" Source user configuration files with set/global sensitivity
	let use_global = get(a:000, 0, ! has('vim_starting'))
```
I can't figure out in which case use_global can be defined by ! has('vim_starting'),could anyone teach me

**Comment by rafi** [comment]
This is a "fancy" mechanism to set options globally in-case of a "hot" reload. The magic happens here:
https://github.com/rafi/vim-config/blob/master/config/filetype.vim#L7-L9

Once one of those files changes, vim automatically reloads configuration, and then, uses a global approach.
