### ISSUE TITLE
make install: &termguicolors must be set 

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#137]
running in iTerm:

make uninstall && mkdir ~/.cache/vim && ./venv.sh && make install

results in:

[dein] Error occurred while executing hook: nvim-colorizer.lua
[dein] Vim(luafile):&termguicolors must be set
[dein] Done: (2020/03/05 15:11:03)[dein] Error occurred while executing hook: nvim-colorizer.lua
[dein] Vim(luafile):&termguicolors must be set

**Comment by RuTom** [comment]
Check if `$COLORTERM` env-variable is set to either `truecolor` or `24bit`

See https://github.com/rafi/vim-config/blob/387ac3af1bdb33ed1766f36bf25aa1452b24f10e/config/general.vim#L28-L32
`termgui` is only set if either `truecolor` or `24bit` is found in the environment variable `COLORTERM`

Assuming `COLORTERM` is not set you have a few options to fix it:
1. Configure iTerm to set the environment variable. iirc it has an option to add custom variables.
2. Include `export COLORTERM=truecolor` in your bashrc/zshrc
3. Change the vim config file accordingly (This makes updating the vim-config harder as your git directory now has local changes)

**Comment by thecontinium** [comment]
Thanks for the suggestions but:

1. `$COLORTERM` is set to `truecolor` 
2. I didn't get this error until recent updates

**Comment by rafi** [comment]
I've recently added the `$COLORTERM` verification at [config/general.vim#L29](https://github.com/rafi/vim-config/blob/master/config/general.vim#L29)

I tried iTerm 3.3.9 just now and it does set the `$COLORTERM` to `truecolor`. What version of iTerm are you using @thecontinium?

**Comment by thecontinium** [comment]
I am using the same iTerm version; running zsh.

I think the problem comes from the fact that when you install from scratch via:

`make uninstall && mkdir ~/.cache/vim && ./venv.sh && make install`

the `make install` starts vim with `$(vim) -V1 -es -i NONE -N -u config/init.vim`and `general.vim` never gets called to `set termguicolors`

If I add `set termguicolors` to config/init.vim on the 1st line; there are no errors.

A different issue but it would be good if `venv.sh `created `~/.cache/vim` if it does not exist as `make uninstall && ./venv.sh` fails with 
```
ln: /Users/thecontinium/.cache/vim/venv: No such file or directory
./venv.sh: line 34: /Users/thecontinium/.cache/vim/venv/bin/pip: No such file or directory
```

cheers

**Comment by rafi** [comment]
Yeah, I see what you mean @thecontinium. I can reproduce it:
```sh
$ rm -r ~/.cache/vim/dein/repos/github.com/norcalli
$ nvim -V1 -es -i NONE -N -u config/init.vim -c "try | call dein#update() | finally | echomsg '' | qall! | endtry"
```

Fixed both suggestions in 35db875c, thanks for reporting.

**Comment by thecontinium** [comment]
cheers

slight typo in venv.sh; change to:

`mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/vim"`

**Comment by rafi** [comment]
thanks, nice catch

**Comment by thecontinium** [comment]
`make uninstall && ./venv.sh && make install` now works

Thx

--
The Continium


On 12 March 2020 at 13:45:10, Rafael Bodill (notifications@github.com<mailto:notifications@github.com>) wrote:

thanks, nice catch
