### ISSUE TITLE
Can't run the venv.sh

### ISSUE THREAD

**Issue by zsinx6** [rafi/vim-config#138]
`/venv.sh: line 36: /home/user/.cache/vim/venv/bin/pip: No such file or directory`

Do I need to create a virtualenv?

**Comment by zsinx6** [comment]
Before this: https://github.com/rafi/vim-config/commit/f97866ed796e1ac6b7463a221f8d25155f595865#diff-081f95f06d8d3d1d1987ced3151f9d66 it worked, so I think something in this commit break the compatibility, mainly on Linux.

**Comment by rafi** [comment]
@zsinx6 can you provide the entire log from running `venv.sh`?
I added further support for pyenv, deprecated python 2, and optimized the script.

Can you also provide the output of these commands?
```sh
$ python3 --version
$ pyenv root
$ ls -alp "$(pyenv root)/versions"
```

**Comment by zsinx6** [comment]
```
$ ./venv.sh 
./venv.sh: line 36: /home/lucas/.cache/vim/venv/bin/pip: No such file or directory

$ python3 --version
Python 3.8.2
$ pyenv root
/home/lucas/.pyenv
$ ls -alp "$(pyenv root)/versions"
total 24
drwxr-xr-x  6 lucas lucas 4096 Mar 10 10:28 ./
drwxr-xr-x 13 lucas lucas 4096 Mar 10 10:28 ../
drwxr-xr-x  6 lucas lucas 4096 Nov 21 16:29 3.7.4/
drwxr-xr-x  6 lucas lucas 4096 Oct 29 16:36 3.7.5/
drwxr-xr-x  6 lucas lucas 4096 Feb 18 09:51 3.8.0/
drwxr-xr-x  6 lucas lucas 4096 Mar 10 10:30 3.8.1/
```

**Comment by rafi** [comment]
@zsinx6 can you try now with 9424cf8a ?

**Comment by zsinx6** [comment]
```
$ ./venv.sh 
:: pyenv not found
===> python3 found
./venv.sh: line 36: /home/lucas/.cache/vim/venv/bin/pip: No such file or directory
```

**Comment by rafi** [comment]
@zsinx6 so what do you have in `/home/lucas/.cache/vim/venv/bin`? does `.cache/vim/venv` exist at all?

**Comment by zsinx6** [comment]
@rafi  After using the old version of the venv.sh, there is a `neovim3` folder, with everything. I tried appending it to the path, but with no success.

**Comment by rafi** [comment]
@zsinx6 Can you try to `rm -rf ~/.cache/vim/venv` and then run the **new** `venv.sh` again?

**Comment by zsinx6** [comment]
It worked

**Comment by zsinx6** [comment]
Don't changed anything, but now doesn't work inside virtualenv

**Comment by rafi** [comment]
The script is just more verbose now, and it doesn't use pyenv by default, it just checks if you created it manually and uses it if you did, like before. If you want to use pyenv, create it first manually: `pyenv virtualenv 3.8.1 neovim`

About virtualenv, did you pip/env install other things into that old virtualenv at `~/.cache/vim/venv/neovim3`?
What doesn't "work" exactly?

**Comment by zsinx6** [comment]
It was not detecting that the neovim has python3 support, after creating the pyevn virtualev, the denite plugin worked and all problems solved.
I think this issue can be closed now.
Thank you @rafi

**Comment by rafi** [comment]
Thanks for reporting and debugging with me. I've added helpful instructions to `venv.sh` per our conversation.
