### ISSUE TITLE
UpdateRemotePlugins overwrite anytime is called

### ISSUE THREAD

**Issue by marcociccone** [rafi/vim-config#139]
Hi, thank you so much for your config file, the work you have done is astonishing and nvim is super fast! I'm trying to adapt it to my needs, so I will probably open more than one issue, sorry about that :P

The first thing that I don't understand is how (and where) can I call `UpdateRemotePlugins` for all the plugins together. For instance I call it the first time that defx plugin fails (after the installation) and it's ok, but then when another plugin needs the update (semshi) and defx is not in the host registered plugins (because I'm not using it I guess) then the update seems to be overwritten and next time I sue defx I need to update it again and so on..

I used to call UpdateRemotePlugins directly when installing the plugin with Plugged, is there a similar way here?
Thanks!

**Comment by rafi** [comment]
Dein package-manager allows lazy-loading and caching, which makes n/vim startup very fast. Because some plugins are lazy-loaded, and require remote plugin initial update, you better use Dein's workaround: `:call dein#remote_plugins()`

I should probably mention it somewhere visible. And thanks for the nice feedback :)

**Comment by marcociccone** [comment]
Thanks! It seems to be working :) Is that all right if I open an issue for any of the other things that are not clear to me or you prefer another way? I have troubles with a couple of plugins

**Comment by rafi** [comment]
Create issues with similar nature.. However if it's concerning plugins features and their internals, you should open issues on the plugin's own github repository.
