### ISSUE TITLE
Markdown expand/collapse E28: No highlight group name: CursorWord0

### ISSUE THREAD

**Issue by mwcm** [rafi/vim-config#140]
Using the readme's table of contents as an example, when I move the vim cursor (using kb or mouse) over line 15 this error is raised, preventing me from expanding:
![Screen Shot 2020-03-13 at 10 43 20 AM](https://user-images.githubusercontent.com/2433319/76631454-1d18b380-6518-11ea-8e6e-2d9a77a438ea.png)

Wondering if there's any way to stop vim-cursorword from highlighting that text, or if you have any other ideas for avoiding this.

**Comment by rafi** [comment]
How up-to-date is your clone of my vim-config? Are you setting the `cursorword_highlight` variable somewhere? It will cause `cursorword#highlight()` to skip setting `CursorWord0` and `CursorWord1` highlight groups and it's the user responsibility then to set them.

If that's not the case, you can try disabling the lazy-load on cursorword plugin:
```diff
 - repo: itchyny/vim-cursorword
-  on_event: FileType
   hook_source: |
     augroup user_plugin_cursorword
       autocmd!
       autocmd FileType defx,denite,qf let b:cursorword = 0
       autocmd WinEnter * if &diff | let b:cursorword = 0 | endif
       autocmd InsertEnter * let b:cursorword = 0
       autocmd InsertLeave * let b:cursorword = 1
     augroup END
```

Remove the `on_event: FileType` line, reload n/vim and run `:call dein#recache_runtimepath()` just to be 100% cache-free, reload vim and try again.

**Comment by mwcm** [comment]
I just updated yesterday from your master after that venv.sh fix. Ahh! Will check if I'm setting `cursorword_highlight` & then try the remove & recache when I have a second...

Thanks so much for the quick reply + all your work on this config! Will have an update sometime this afternoon.

**Comment by mwcm** [comment]
to follow up: i restarted the macbook Friday night and it went away 🤦‍♂ 
didn't happen at all this weekend on my computer at home either
thanks for your time! 😄
