### ISSUE TITLE
Suggestion: Keep Defx in line with window directory changes 

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#141]
Hi  

You might like to include this to keep defx in track with directory changes when it is open.
e.g. using Denite z 

``` vim
autocmd user_events DirChanged * if bufwinnr('tab'.tabpagenr()) != -1
  \ |  let cw = winnr()
  \ |  Defx -toggle  -buffer-name=tab`tabpagenr()`
  \ |  execute('lcd ' . v:event['cwd'] )
  \ |  Defx -toggle `getcwd()` -buffer-name=tab`tabpagenr()`
  \ |  execute(cw .'wincmd w')
```

**Comment by rafi** [comment]
Thanks @thecontinium! I've been trying to figure out this for a while now. However, in the past I've noticed that `DirChanged` triggers also when moving between windows/tabs with different working-directory.

But I'll try this snippet, I'll let you know :)

**Comment by rafi** [comment]
Works great @thecontinium. I've added a fix for the case when changing directory after closing defx, once you open defx again, it will load correct directory.

```vim
" Handle working-directory changes appropriately
autocmd DirChanged * if bufwinnr('tab'.tabpagenr()) != -1
	\ |   let cw = winnr()
	\ |   Defx -toggle -buffer-name=tab`tabpagenr()`
	\ |   execute('lcd ' . v:event['cwd'])
	\ |   Defx -toggle `getcwd()` -buffer-name=tab`tabpagenr()`
	\ |   execute(cw . 'wincmd w')
	\ | elseif bufnr('tab' . tabpagenr()) != -1
	\ |   execute(bufnr('tab' . tabpagenr()) . 'bwipeout')
	\ | endif
```

**Comment by mn-dimension** [comment]
trying it out thx - good to see you back amending the config.

**Comment by rafi** [comment]
Defx replaced by Fern.
