### ISSUE TITLE
Error when running Make for fresh install with Vim8

### ISSUE THREAD

**Issue by chrischen** [rafi/vim-config#144]
With fresh install, I run `./venv.sh` with a virtualenv I created called "neovim". It works fine without error, but then I encounter this during make.

```
[dein] (118/142) [++++++++++++++++----] vim-cursorword
[dein] (122/142) [+++++++++++++++++---] sideways.vim
[dein] (126/142) [+++++++++++++++++---] asyncomplete.vim
[dein] (130/142) [++++++++++++++++++--] helpful.vim
[dein] (134/142) [++++++++++++++++++--] vim-which-key
[dein] (138/142) [+++++++++++++++++++-] neco-vim
[dein] Error occurred while executing hook: vim-indent-guides
[dein] Vim(redir):E930: Cannot use :redir inside execute()
[dein] Done: (2020/04/22 01:37:01)%
```

```
[dein] (131/141) [++++++++++++++++++--] python_match.vim
[dein] (132/141) [++++++++++++++++++--] php.vim
[dein] (133/141) [++++++++++++++++++--] vim-which-key
[dein] (134/141) [+++++++++++++++++++-] vim-git
[dein] (135/141) [+++++++++++++++++++-] neomru.vim
[dein] (136/141) [+++++++++++++++++++-] vim-jsdoc
[dein] (138/141) [+++++++++++++++++++-] vim-denite-session
[dein] (139/141) [+++++++++++++++++++-] vim-altr
[dein] Done: (2020/04/22 01:36:47)[dein] Error occurred while executing hook: vim-indent-guides
[dein] Vim(redir):E930: Cannot use :redir inside execute()
not found in 'packpath': "pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
[dein] Update started: (2020/04/22 01:36:47)
```

When running `<space> f e` I get
```
[vim-hug-neovim-rpc] failed executing: pythonx import [pynvim|neovim] 
```

This setup works fine in neovim, just not in vim8.

**Comment by chrischen** [comment]
Ok I fixed the python import problem. I installed vim/macvim via homebrew and it was using the homebrew python3 instead of the pyenv python3. I then had to install `pip install neovim` in order to fix it though.

However still getting
`[dein] Vim(redir):E930: Cannot use :redir inside execute()` on startup.

**Comment by rafi** [comment]
Hi @chrischen. Unfortunately there isn't a simple way to set the python interpreter with Vim, therefore installing with `pip` is the right way. Notice! You should install `pynvim`, not `neovim`. The latter is an old name that is being deprecated.

Regarding the `:redir` error, I pushed 6db7c8c4 which should solve this. Let me know.

**Comment by chrischen** [comment]
The reason I installed pip neovim is because is because it was giving an error saying it could not import neovim. For the record, pynvim was in fact installed, and I still had to install neovim via pip to get rid of the error and to have defx work.

**Comment by rafi** [comment]
If you're using vim8 (not Neovim), you need to install `pynvim` with the python interpreter that is linked to your vim8 installation. Unlike Neovim, you can't select the python interpreter with vim8.

So, for example, if you use `pyenv`, you can select your system's interpreter and install accordingly:
```sh
# View a list of python interpreters installed in your OS
$ pyenv versions
# Select the system interpreter
$ pyenv global system
# Install required neovim libraries
$ pip3 install pynvim
```

**Comment by rafi** [comment]
I've improved the Makefile and fixed the `packpath` warnings at https://github.com/rafi/vim-config/commit/b7cd3b85ea8012ce91892cb68fa5847a3a87012d -- please reopen if there's still an issue.
