### ISSUE TITLE
Yank doesn't seem to work in Vim8 if nvim also installed

### ISSUE THREAD

**Issue by chrischen** [rafi/vim-config#145]
It seems if you do yank in vim8 it doesn't go into the yank history. But if you open neovim and yank, it shows up in the history in vim8.

Put (pasting) in vim8 then does not work. Interestingly enough OS clipboard works.

**Comment by chrischen** [comment]
I found the issue in line 48 of `general.vim`

```
if has('clipboard') && has('vim_starting')
	set clipboard& clipboard+=unnamedplus
endif
```

Not sure why it causes the problem in vim8 but not in neovim though.

**Comment by chrischen** [comment]
Was able to fix by changing to

```
if has('clipboard') && has('vim_starting')
	set clipboard& clipboard^=unnamed,unnamedplus
endif
```

Thanks to https://stackoverflow.com/questions/30691466/what-is-difference-between-vims-clipboard-unnamed-and-unnamedplus-settings.

Works in both vim and neovim now. I will do a pull request tomorrow.

**Comment by rafi** [comment]
Hi @chrischen - are you referring to __numbered registers_? e.g. `"1..9`?
These are only for deletions, not yanks. Try testing with just deletions.

**Comment by rafi** [comment]
@chrischen What is your OS? What's your output for `:echo g:clipboard` ?

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, check it out...
