### ISSUE TITLE
How to enable elite mode?

### ISSUE THREAD

**Issue by Itailevi420** [rafi/vim-config#148]
Well maybe it's a stupid question but I can't seem to enable elite mode.
_reproducing actions:_
- `echo 'let g:elite_mode = 0'  >> ~/.config/nvim/config/.vault.vim`
 and tried with "1" int and 'true' boolean  values as well, and tried a different file name `local.vim`
and didn't work.
eventually I commented out 2 lines (basically the _if_ statement)  in ` ~/.config/nvim/config/mappings.vim`
```
 " Elite-mode {{{ 
 " ----------                                                     
"if get(g:, 'elite_mode')  
 " Disable arrow movement, resize splits instead.          
                   nnoremap <silent><Up>    :resize +1<CR>     
                   nnoremap <silent><Down>  :resize -1<CR>  
                   nnoremap <silent><Left>  :vertical resize +1<CR>     
                   nnoremap <silent><Right> :vertical resize -1<CR> 
"endif  
```
what am I doing wrong?
BTW 
great job thanks alot.

**Comment by donskies** [comment]
Put .vault.vim in ~/.config/nvim/ rather than ~/.config/nvim/config/

echo 'let g:elite_mode = 1' >> ~/.config/nvim/.vault.vim

**Comment by rafi** [comment]
@Itailevi420 the correct location is `~/.config/nvim/.vault.vim` like donskies mentioned.
