### ISSUE TITLE
Invalid argument: diffopt+=internal,algorithm:patience

### ISSUE THREAD

**Issue by mimicode** [rafi/vim-config#149]
Error detected while processing /Users/zhang/.config/nvim/config/general.vim:
line  209:
E474: Invalid argument: diffopt+=internal,algorithm:patience
Press ENTER or type command to continue

**Comment by rafi** [comment]
@mimicode thanks for reporting.
Are you using neovim or vim? Could you include `nvim --version` or `vim --version` here?

**Comment by virackt** [comment]
I met the same problem. And nvim --version prints: 
`NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local`

**Comment by rafi** [comment]
@mimicode @virackt please try latest commit
