### ISSUE TITLE
cheat sheet

### ISSUE THREAD

**Issue by raivivek** [rafi/vim-config#15]
The config is very nice. It'd be great if there is a handy cheat sheet.

**Comment by raivivek** [comment]
I think your README does a good job of documenting what I desired 3 years ago now! :) So, closing this. Thanks!

**Comment by rafi** [comment]
@raivivek I've greatly improved the [custom key-bindings](https://github.com/rafi/vim-config#custom-key-mappings) section in README.md a few days ago, check it out.
