### ISSUE TITLE
Colorscheme issues: missing parts

### ISSUE THREAD

**Issue by PaxSov** [rafi/vim-config#151]
I am using a completely unmodified version of your config.
I am using neovim
My font is Hack Nerd Font Mono
This is what happens with any colorscheme other then hybrid
![2020-05-29-204429_1920x1080_scrot](https://user-images.githubusercontent.com/63252513/83298980-e7b16700-a1e4-11ea-9306-767fa7922e36.png)

**Comment by rafi** [comment]
I'm using `hybrid` colorscheme, and [`./themes/hybrid.vim`](./themes/hybrid.vim) only triggers for hybrid.
So the statusline and tabline are quite colorless, yes. You can use lightline or airline, they are very popular.
Hope I'll have time soon to improve my custom tab/statuslines.

**Comment by rafi** [comment]
Tabline and statusline have been improved to make an effort and adapt to current colorscheme colors.
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, check it out...
