### ISSUE TITLE
Expand Selection Broken

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#156]
Selecting with `C-v` and then pressing `v/V `is not working after the latest changes.

**Comment by rafi** [comment]
Thanks. I might be because of the `deris/vim-shot-f` plugin.

**Comment by dangkhoasdc** [comment]
I checked, the issue comes from `vim-sandwich` plugin. Turn it off and `vim-expand-region` is able to work as expected.

**Comment by thecontinium** [comment]
cheers - I'll take a look

**Comment by rafi** [comment]
I already fixed this conflict with 61fd6950. Please reopen if still occuring..
