### ISSUE TITLE
Add: Gina branch in status 

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#157]
You may like to add the branch to the status buffer; useful to see branch and whether ahead or behind.

call gina#custom#command#option('status', '-b')

**Comment by rafi** [comment]
Gina is really great. I've been wanting to optimize more things to use Gina.
Thanks for this suggestion, I'll leave this opened until I have time to catchup.

**Comment by thecontinium** [comment]
Yes I like it too; use it all the time now; using a default vsplit on status I also like.

**Comment by rafi** [comment]
Added and improve Gina, thanks.
