### ISSUE TITLE
mapping conflicts with cib, cab

### ISSUE THREAD

**Issue by wynnej1983** [rafi/vim-config#160]
- WARNING: Conflicting mapping found:
    ab → <Plug>(textobj-sandwich-auto-a)
    b → {'pair': [{'c': ')', 'o': '('}, {'c': ']', 'o': '['}, {'c': '}', 'o': '{'}]}
  - WARNING: Conflicting mapping found:
    ib → <Plug>(textobj-sandwich-auto-i)
    b → {'pair': [{'c': ')', 'o': '('}, {'c': ']', 'o': '['}, {'c': '}', 'o': '{'}]}
  - WARNING: Conflicting mapping found:
    a, → <Plug>SidewaysArgumentTextobjA
    , → {'separator': [{'d': ','}]}
  - WARNING: Conflicting mapping found:
    i, → <Plug>SidewaysArgumentTextobjI
    , → {'separator': [{'d': ','}]}

**Comment by rafi** [comment]
Can you try latest commit?

**Comment by wynnej1983** [comment]
@rafi pulled lastest commit. now when i cib or cab it doesnt work if i type if quickly, i need to wait a bit for it to work eg: ca....b which is annoying

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, check it out...
