### ISSUE TITLE
Lag in large go files

### ISSUE THREAD

**Issue by sergiopatino** [rafi/vim-config#163]
Curious about these lines. Have you noticed any lag in large go files +1000 lines? I traced it down to these lines. When commented it out it goes away:

https://github.com/rafi/vim-config/blob/ac06301f49110fb1d3004b94695e85e04731c1f7/config/plugins/lsp.vim#L8-L10

**Comment by sergiopatino** [comment]
Seems related to this:
https://github.com/prabirshrestha/vim-lsp/issues/671

**Comment by rafi** [comment]
I do experience lags. Also in markdown, plasticboy/vim-markdown's folding is slow.
I'm thinking about disabling them all. Thanks for posting!

**Comment by sergiopatino** [comment]
A compromise may be to toggle this on a per file bases via a key mapping or more ideally set a threshold to disable based on file size.

**Comment by rafi** [comment]
Dropped vim-lsp in-favor of Neovim's built-in LSP.
