### ISSUE TITLE
syntax badge uses lsp even when the server is not active

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#164]
I still use ale for syntax tracking for some languages but the check whether to use lsp in badge.vim   	

`if exists('*lsp#ui#vim#diagnostics#get_buffer_diagnostics_counts')
`

is always true even when a server is not setup for that language and stops ale being used.

can you test for `g:lsp_diagnostics_enabled = 1` instead ?

**Comment by rafi** [comment]
Can you test fbb53884?

**Comment by mn-dimension** [comment]
fixed - thanks

**Comment by thecontinium** [comment]
fixed
