### ISSUE TITLE
Python provider

### ISSUE THREAD

**Issue by zsinx6** [rafi/vim-config#165]
In the last version there is a problem with the python provider:

```
  - WARNING: pyenv is not set up optimally.
    - ADVICE:
      - Create a virtualenv specifically for Neovim using pyenv, and set `g:python3_host_prog`.  This will avoid the need to install the pynvim module in each version/virtualenv.
```

I corrected this in `config/init.vim`:
`let g:python3_host_prog = '~/.cache/vim/venv/bin/python3'`

I think this wasn't a problem in previous commits

**Comment by rafi** [comment]
What happens if you run `./venv.sh` ?

**Comment by zsinx6** [comment]
It creates the venv I used in the path, but don't set the `python3_host_prog`

**Comment by rafi** [comment]
@zsinx6 is your `~/.cache/vim/venv` a directory or a symlink?

**Comment by zsinx6** [comment]
A directory

**Comment by rafi** [comment]
Can you try cea99405? I've changed how `venv.sh` creates the venv when pyenv is available.. now it uses it, symlinked or not.

**Comment by zsinx6** [comment]
There is a problem in https://github.com/rafi/vim-config/blob/cea99405ff53bb4a05ad023a33454dc44603684c/venv.sh#L12 but now I thinks its is behaving as expected
```
ln: invalid option -- 'h'
Try 'ln --help' for more information.
```

**Comment by rafi** [comment]
@zsinx6 what OS do you use? I remove `-h` in d1818077. Don't think it's necessary.

**Comment by zsinx6** [comment]
Arch Linux, when removed it worked. But it is still missing the link to python3_host_prog, I need to set it manually

**Comment by zsinx6** [comment]
@rafi do you think it can be set in init.vim?

**Comment by rafi** [comment]
@zsinx6 there is no dependency on the python provider anymore. Everything is Lua based.
