### ISSUE TITLE
Defx with vim-choosewin to select window on file open

### ISSUE THREAD

**Issue by cj** [rafi/vim-config#166]
coc-explorer has a great feature https://github.com/weirongxu/coc-explorer/blob/master/autoload/coc_explorer/select_wins.vim only if you have multiple windows open it allows you to choose the window buffer to open the file in.  As we use https://github.com/t9md/vim-choosewin we could use that to allow you to choose which window to open the file in selected from defx.

Here is an example for NERDTree https://github.com/weilbith/nerdtree_choosewin-plugin

**Comment by rafi** [comment]
@cj use <kbd>Ctrl</kbd>+<kbd>CR</kbd> to trigger `<Plug>(fern-action-open:select)` which has a choosewin interface.
