### ISSUE TITLE
Is there a shortcut key for toggling paste mode?

### ISSUE THREAD

**Issue by yusiwen** [rafi/vim-config#167]
Manually, it can be set with `:set paste` and unset with `:set nopaste`, but  I would like some shortcut for toggling paste mode before and after pasting some long formatted textx. I've search the config files roughly and can't find one. Is there some configs, plugins available? Thanks.

**Comment by rafi** [comment]
Hi @yusiwen. You can create your own `config/local.vim` and add:
```viml
nnoremap <F2> :set invpaste paste?<CR>
imap <F2> <C-O>:set invpaste paste?<CR>
set pastetoggle=<F2>
```

This will toggle paste mode using <kbd>F2</kbd>.

However, with Neovim you don't need it. And you might want to try this with Vim to set paste automatically without toggling:
https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/unix.rc.vim#L41-L53

**Comment by yusiwen** [comment]
@rafi Thanks for reply. I'm not very familiar with Neovim, why it's not needed on Neovim?
