### ISSUE TITLE
<C-Tab> does not work as expected (Jump outside of pair)

### ISSUE THREAD

**Issue by Wansmer** [rafi/vim-config#168]
First off, thanks for a great job!
According to the `README`, I press `<C-Tab>` in INSERT mode to jump over closed paired characters, but instead navigate through the autocomplete options.
The same behavior is observed for any combination that contains `<Tab>`.
I tried to reassign `imap <buffer> <expr> <C-Tab> l delimitMate # JumpAny()` in `config/plugins/all.vim` to various hotkeys, but it didn't work.
Also when I open `:imap` I see that the `<C-Tab>` is assigned the following: `i <C-Tab> * <C-R> = UltiSnips#ListSnippets() <CR>`

I'm new to vim, maybe I'm doing something wrong?
Thanks for the help!

**OS:** MacOs 10.15.7
**NVIM:** v0.4.4

**Comment by rafi** [comment]
Hi @Wansmer. Can you try in insert-mode between pairs to press <kbd>Ctrl</kbd>+<kbd>g</kbd> <kbd>g</kbd> and see if it works?

**Comment by Wansmer** [comment]
Hello! Yes, it's works. Thank you!
