### ISSUE TITLE
how to add more plugin by vundle?

### ISSUE THREAD

**Issue by KaimingWan** [rafi/vim-config#169]
I need to add more plugin. Where can I config to add plugin by vundle

**Comment by SolarAquarion** [comment]
you don't add plugins by vundle, you use dein.

**Comment by rafi** [comment]
@KaimingWan create a file named `config/plugins.local.yaml` and add plugins. See `config/plugins.yaml` for examples and [Shougo/dein.vim](https://github.com/Shougo/dein.vim) for help.
