### ISSUE TITLE
"Cannot find color scheme 'hybrid'"

### ISSUE THREAD

**Issue by alexbooker** [rafi/vim-config#17]
When I open Neovim, I get this error:

```
Error detected while processing /home/booker/.vim/config/theme.vim:
line   20:
E185: Cannot find color scheme 'hybrid'
Press ENTER or type command to continue

```

**Comment by rafi** [comment]
To quickly fix this, restart Neovim. If that doesn't work, try `make update`, it will clear the plugin-manager's state.

Reason is [one](https://github.com/rafi/awesome-vim-colorschemes) of the plugins I'm [using](https://github.com/rafi/vim-config/blob/master/config/plugins.vim) is a collection of colorschemes, and adding them with [`dein#local`](https://github.com/rafi/vim-config/blob/master/config/vimrc#L44). For some reason the first it gets installed, it won't get added to the `runtimepath`. Still trying to figure it out...

**Comment by alexbooker** [comment]
Thanks :smile:
