### ISSUE TITLE
Wordy error

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#170]
Hi 

Just started using `Wordy` and I get this error:

`:Wordy weak `results in `Warning: Cannot find word list "weak.utf-8.spl" or "weak.ascii.spl"`

Do this work for you?

Works ok when this is removed:   `hook_add: let g:wordy_spell_dir = $DATA_PATH . '/wordy'`

cheers

**Comment by thecontinium** [comment]
This fixes it for me:

```
- repo: reedes/vim-wordy
  on_cmd: [ Wordy, NoWordy, NextWordy ]
  hook_add: |-
    let g:wordy_spell_dir = $DATA_PATH . '/wordy'
    set runtimepath+=g:wordy_spell_dir

```

**Comment by rafi** [comment]
Not installed anymore.
