### ISSUE TITLE
Asyncomplete not registering sources

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#172]
Open neovim
`:echo asyncomplete#get_source_names() `=> []

adding `autocmd VimEnter * doautocmd <nomodeline> User asyncomplete_setup` in `local.vim` is a temp workaround

**Comment by rafi** [comment]
Interesting @thecontinium. Could you show your YAML configuration and how you use asyncomplete?

**Comment by thecontinium** [comment]
Hi @rafi  If I remove my `local.vim` and` local.plugins.yaml` then on startup if I `:echo asyncomplete#get_source_names()` => []
Do you have it populated ?

**Comment by rafi** [comment]
👋 On entering vim with empty file, it shows empty `[]`, but as soon as a file is edited it is populated. Why would need asyncomplete loaded on an empty file?

Unless you're opening a file straight from command-line e.g. `nvim file.md`, the completion stack is entirely lazy-loaded in this order:
- `asyncomplete.vim`
- `asyncomplete-lsp.vim`
- `vim-lsp`
- `vim-lsp-settings`

All the asyncomplete extensions are loaded before `vim-lsp-settings`. Maybe that's the issue. They probably need to load before `asyncomplete.vim`, and not `vim-lsp-settings` i.e. `on_source: asyncomplete.vim`.

What do you think @thecontinium ?

**Comment by mn-dimension** [comment]
Bit more investigation using `dein#is_sourced(...)`shows that either of the `on_source` actually works. Like you suggest on_source: `asyncomplete.vim` probably makes more sense for sources like tags, buffers, look, snip ... that are unrelated to lsp but have a large usage across file types.

Seems that if you open with `nvim` the asyncomplete source list is empty and when you then edit any file `:e dfd` asyncomplete adds the source_names() and `echo asyncomplete#get_source_names()` shows entries for all of the loaded sources.

With the clause `on_event: [ BufReadPre, VimEnter ]` on `vim-lsp-settings` we are in effect making this plugin and all the plugins with `on_source vim-lip-settings` and up the chain to `asyncomplet.vim` and any that are then `on_source asyncomplete.vim` all **non** lazy. If you open up with `nvim` and :`echo dein#is_sourced(...)` you will see that they are all sourced. I guess the benefit is that the loading happens after you are in and can start typing whilst it loads them in the background ?

I think you can close this now - cheers.

**Comment by thecontinium** [comment]
Bit more investigation using dein#is_sourced(...)shows that either of the on_source actually works. Like you suggest on_source: asyncomplete.vim probably makes more sense for sources like tags, buffers, look, snip ... that are unrelated to lsp but have a large usage across file types.

Seems that if you open with nvim the asyncomplete source list is empty and when you then edit any file :e dfd asyncomplete adds the source_names() and echo asyncomplete#get_source_names() shows entries for all of the loaded sources.

With the clause on_event: [ BufReadPre, VimEnter ] on vim-lsp-settings we are in effect making this plugin and all the plugins with on_source vim-lip-settings and up the chain to asyncomplet.vim and any that are then on_source asyncomplete.vim all non lazy. If you open up with nvim and :echo dein#is_sourced(...) you will see that they are all sourced. I guess the benefit is that the loading happens after you are in and can start typing whilst it loads them in the background ?

I think you can close this now - cheers.
