### ISSUE TITLE
No colors in MacOS iterm2 

### ISSUE THREAD

**Issue by defp** [rafi/vim-config#176]
![image](https://user-images.githubusercontent.com/612381/102333139-f831ff00-3fc7-11eb-9362-0ae6cb53c001.png)

```
❯ echo $TERM
xterm-256color
```

**Comment by rafi** [comment]
Hi @defp, seems like your terminal doesn't support 24bit true-color.

Can you try to `export COLORTERM=256` and run n/vim immediately after?

**Comment by defp** [comment]
not work
item2
![image](https://user-images.githubusercontent.com/612381/102633933-134d6c00-418c-11eb-97d6-f2784fa11835.png)

terminal.app

![image](https://user-images.githubusercontent.com/612381/102634112-5a3b6180-418c-11eb-83dc-eebf4e6041b6.png)

**Comment by defp** [comment]
```
:syntax on
```

![](https://cos.ap-beijing.myqcloud.com/dropshare-1252438752/pb-baTWypJ6Wh.png)

**Comment by PegasusWang** [comment]
@defp Try install `nerd-font` to show special character in terminal.

**Comment by rafi** [comment]
@defp fixed in 7d665f4

**Comment by defp** [comment]
👏👏👏
