### ISSUE TITLE
copy on select in vim

### ISSUE THREAD

**Issue by sundar-h** [rafi/vim-config#178]
I turn on the "copy to pasteboard on selection" option, but it does not take effect in nvim while use this repo as my config.
While nvim -u specify an empty init.vim file, it take effect again.
I've tried those bellow: 
1. uncomment all clipboard settings
2. set clipboard=unnamedplus i local.vim
3. set clipboard=unnamedplus in local.vim
but it has no effect too.

What should I do about it?

**Comment by rafi** [comment]
Hi @sundar-h, can you tell me what's your output for `:echo &clipboard` when you start with `nvim -u NONE`?

In line #49 in `config/general.vim` -- try changing the `set clipboard& clipboard^=unnamed,unnamedplus` line to `set clipboard& clipboard+=unnamedplus` .. let me know.

**Comment by rafi** [comment]
Try `set clipboard=unnamed` @sundar-h
