### ISSUE TITLE
I'm getting an empty plugin list when i try to update plugins on my fork

### ISSUE THREAD

**Issue by SolarAquarion** [rafi/vim-config#179]
https://github.com/SolarAquarion/vim-config

I'm currently testing things with neovim to see how my changes are going and there's obviously some things to add to my plugins.yaml, but i don't know what is going on that is making the plugins a failure to update or install

**Comment by SolarAquarion** [comment]
i fixed the lack of loading, but that was replaced by a jq/yq error 

[config/init] 'Vim(return):E474: Unidentified byte: jq: Unknown option -I^@Use jq --help for help with command-line options,^@or see the jq manpage, or online docs  at https://stedolan.github.io/jq^@yq: Error running jq: ScannerError: mapping values are not allowed here^@  in "<stdin>", line 675, column 12.^@'
[config/init] Error loading /home/solaraquarion/.config/nvim/config/plugins.yaml
[config/init] Caught: 'Vim(return):E474: Unidentified byte: jq: Unknown option -I^@Use jq --help for help with command-line options,^@or see the jq manpage, or online docs  at https://stedolan.github.io/jq^@yq: Error running jq: ScannerError: mapping values are not allowed here^@  in "<stdin>", line 675, column 12.^@'
[config/init] Unable to read configuration files at ['/home/solaraquarion/.config/nvim/config/plugins.yaml']
Error detected while processing function <SNR>1_main[43]..<SNR>1_use_dein[29]..<SNR>1_parse_config_files:
line   10:
Vim(let):E712: Argument of extend() must be a List or Dictionary
Error detected while processing function <SNR>1_main[43]..<SNR>1_use_dein:
line   29:
E171: Missing :endif

**Comment by rafi** [comment]
Make sure that your `plugins.yaml` is a well-formed YAML.

**Comment by SolarAquarion** [comment]
i fixed my plugins.yaml file with a linting
