### ISSUE TITLE
Question about Makefile

### ISSUE THREAD

**Issue by alexbooker** [rafi/vim-config#18]
I am running Neovim 0.1.2.

When I run `make test` I get an error:

![](http://i.imgur.com/zuTsc3E.png)

I also get an error when I run `make install`

![](http://i.imgur.com/Qk0jZqM.png)

I'm a bit confused because these commands are based on Vim not Neovim. I appreciate that these commands are under the **Vim** heading but because the **Neovim** instructions assume you have already run `git clone git://github.com/rafi/vim-config.git ~/.vim`, I inferred you need to run the **Vim** and **Neovim** instructions. 

Can you please clarify? Thanks.

**Comment by rafi** [comment]
Hey Alex, thanks for the feedback and sorry it took me time to reply.
1. Neovim 0.1.4 was released a week ago, recommended :)
2. I've updated the `Makefile` and README section of installation to something more reasonable hopefully.

Could you please re-read the [install](https://github.com/rafi/vim-config#install) section and try updating my config with `make update`? (it performs `git pull` as well).

**Comment by alexbooker** [comment]
Thanks for getting back to me, @rafi 

I managed to get your config working in Neovim and copied all the Unite stuff I liked :smile:
