### ISSUE TITLE
Feature request: don't map quit & macro shortcuts

### ISSUE THREAD

**Issue by stonemaster** [rafi/vim-config#181]
First of all, thanks a lot for your awesome VIM configuration  which I am actively using every day and to which I now migrated all my development activity!

How difficult would it be to have the behavior that `q`/`Q` are remapped to closing the last window configurable? I personally don't like this default and would like to have `q` be the standard macro recording feature. Additionally I am hitting `q` too much by accident on my keyboard :-D

I tried to remove the mapping in my `local.vim` file but I unfortunately couldn't undo this mapping. The same trick worked fine for the `Y` remapping so maybe there is some advanced trick for this.

**Comment by rafi** [comment]
Glad you're enjoying my effort. I really got used to <kbd>q</kbd> quitting a window, but often thought about remapping it to <kbd>Leader</kbd><kbd>q</kbd>.

Try creating `.vault.vim` in your root vim-config, 
```viml
nmap q q
```

I'll think of a better way to disable this.

**Comment by stonemaster** [comment]
Thank you for your answer! I tried the `.vault.vim` trick but unfortunately this didn't unmap `Q`. I am using Neovim Nightly btw.

**Comment by PongPong** [comment]
I have the same trouble when navigating quick fix list which often quit my vim or last window accidentally.

**Comment by rafi** [comment]
I tried getting used to `:q`/`<Leader>q`/`sq`, but I guess I'm too immersed in <kbd>q</kbd>.
Added an option to disable this in your `.vault.vim`:
```viml
let g:enable_universal_quit_mapping = 0
```
3cd1ff01 and 5bdb7df8
