### ISSUE TITLE
closing diff buffer

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#192]
thanks for your great **nvim branch**! Love it :-)

~~two~~ one small thing~~s~~ I struggle with: 

1. diff buffer (e.g. `:Gina diff`): pressing `q` in a diff buffer closes nvim fully and not just the buffer. Could this be fixed for example by mapping `bd` to `q` for diff buffers?
~~2. if I open nvim without a file (simply by the shell command `nvim`) and press `enter`  in the empty buffer `<Plug>delimitMateCR` is inserted instead moving the cursor down a line. This is not the case if I I open a file with nvim (`nvim my_file.txt`) and then open additionally an empty buffer by `tabnew`~~

Branch: `nvim`
System: `Linux Mint 20 Ulyana`
Terminal: `GNOME Terminal 3.36.2`

**Comment by rafi** [comment]
Hi @kraxli. Gina diff opens by default in the same buffer, so you can press <kbd>Ctrl</kbd>+<kbd>o</kbd> or <kbd>Ctrl</kbd>+<kbd>6</kbd> or <kbd>sb</kbd> to return to previous buffer or <kbd>sx</kbd> to delete buffer but retain window.

You can change the default behavior of `:Gina diff` with:
```vim
call gina#custom#command#option('/\v(diff|d)$', '--opener', 'tabnew')
call gina#custom#command#alias('diff', 'd')
```
This will cause `:Gina diff` to appear in a new tab, and alias `:Gina d` too.

See more at [lambdalisue/gina.vim](https://github.com/lambdalisue/gina.vim).
