### ISSUE TITLE
Error showing badge

### ISSUE THREAD

**Issue by ialiendeg** [rafi/vim-config#193]
Hi Rafi, I'm having an error when I develop ruby on rails.

It complaints about wrong parameters for the printf call in badge, and I think it's actually wrong, it should be l:info (autoload/badge.vim:255):

```
	if l:info > 0
		let l:msg .= printf(' %d ', l:information)
	endif
```
I made a PR for you (I tested in local and seems to fix the issue).

**Comment by rafi** [comment]
Thanks, there were major changes lately. This has already been fixed.
