### ISSUE TITLE
Focus-stealing when deleting

### ISSUE THREAD

**Issue by mm1ke** [rafi/vim-config#196]
Hi,

For some time now i had a issue when deleting something (line, word, char) in neovim. 
It looked like everytime i deleted (with `d` + `l`) anything, konsole/neovim lost the focus. When deleting again, focus was again on neovim/konsole. This was switching every time i deleted anything. 
However it's not really that it looses the focus, i'm still able to write something or use other `vi` shortcuts, but it has the same appearance since the cursor bar looks empty instead of being filled (don't know exactly how to explain):

It looks like this:
![image](https://user-images.githubusercontent.com/2951173/125169510-d8079e80-e1aa-11eb-9a22-e3cf61373152.png)
instead of this:
![image](https://user-images.githubusercontent.com/2951173/125169589-32a0fa80-e1ab-11eb-9921-795439a7a325.png)

This also has the effect that other (global) kde shortcuts doesn't work correctly too when out of focus (like i have `Meta` + `l` and `Meta` + `j` to switch between konsole tabs). Even after exiting `neovim` focus is not really on the konsole window (though, i'm still able to write) which means i had to click on the window in order to gain focus again or start vi, type something, delete something and quit again - very annoying.

Anyway i found the culprit and it came with bfbeb247f7a274c85240f67b626840202e6e2ab1
Especially following change:
```diff
if has('clipboard') && has('vim_starting')
-       set clipboard& clipboard+=unnamedplus
+       " set clipboard& clipboard+=unnamedplus
+       set clipboard& clipboard^=unnamed,unnamedplus
 endif
```

Don't know why or how this affects me but reverting this makes it work again. I also think it's related to the environment. On a headless system i don't have this problem. Also when using a different terminal i don't have this problem.
I'm fine if this can't be fixed somehow, personally i can fix it locally but i also wanted to let you know, maybe someone else have the same problem. 
BTW, i've also tried it with completely new users to see to see if it's a profile problem, but i had it there too..

My environment is:
KDE using konsole 21.04.3 on Wayland
Neovim version is 0.5.0

**Comment by rafi** [comment]
hi @mm1ke. Is your `g:clipboard` set? What does `:echo g:clipboard` shows you?

**Comment by mm1ke** [comment]
Hi rafi,

I've checked both versions and with both i've got following output:
` E121: Undefined variable: g:clipboard`

**Comment by rafi** [comment]
@mm1ke it seems the behavior is different on macOS/Linux/Windows.

Could you try replacing that line with `set clipboard^=unnamed`
all-together and see if it works?

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, check it out...
