### ISSUE TITLE
nvim branch: slow loading of markdown files

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#197]
Do you have very slow loading of markdown files ?
I have turned off treesitter; lsp diagnostics and the markdown plugin  but it  is still slow !

do you know what is causing it ?

**Comment by rafi** [comment]
Probably folds...

**Comment by thecontinium** [comment]
I think it is folds and sessions that causes the problem.

**Comment by rafi** [comment]
thanks for sharing!

**Comment by rafi** [comment]
I tried a few times finding a better alternative to sleuth.. to no avail.
