### ISSUE TITLE
Tinyline symbols not showing

### ISSUE THREAD

**Issue by vakosel** [rafi/vim-config#2]
Arrows and master icons not showing in my vim . Terminal urxvt  -unicode 3 enabled 
and various patched fonts used . ( Menlo for Powerline , Inconsolata for Powerline, Terminus for Powerline)
.All these fonts show the icons when i use Terminator .But in this case vim and vimrc are unusable  with weird characters mainly with BS and Del. 
Any help would be appreciated. Thanks

**Comment by vakosel** [comment]
Trial and error gave me the rt solution So just for let other people with the same problem  find  a solution , i used various combination of fonts (after ensuring that my locale was en_US.UTF8) and finally :+1: 
my .Xresources setting ,
URxvt.font:           xft:PragmataPro:Regular:size=13, xft:Terminess Powerline:size=11 
The second as a fall back made the trick .you can find it here : https://github.com/powerline/fonts
Bye for now and well done for you work again.Simply amazing

**Comment by rafi** [comment]
Thank you so much. Check out my [.config/xorg/Xresources](https://github.com/rafi/.config/blob/master/xorg/Xresources)
