### ISSUE TITLE
Receiving error fatal: could not create leading directories of '/nvim/dein/repos/github.com/Shougo/dein.vim': Read-only file system

### ISSUE THREAD

**Issue by kuttor** [rafi/vim-config#201]
So I have used your config a ton, but on this new MacOSX system, I do your exact steps to install and get the following error

fatal: could not create leading directories of '/nvim/dein/repos/github.com/Shougo/dein.vim': Read-only file system

I am wondering if the reason is its trying to put it in the root /nvim?

**Comment by rafi** [comment]
Hi @kuttor, could you try with latest update?

**Comment by kuttor** [comment]
Yup the worked.

**Comment by kuttor** [comment]
What was the issue? It looked like nvim wasn't going to home.

**Comment by rafi** [comment]
@kuttor nvim respects `$XDG_DATA_HOME` environment variable, however some people don't set it so I added the default setting in 68f90133.
