### ISSUE TITLE
is there a wayto get italics for comments and such?

### ISSUE THREAD

**Issue by kuttor** [rafi/vim-config#205]
tried several solutions couldnt get it working. figured id ask ya. 

love the repo by the way

**Comment by rafi** [comment]
Hi @kuttor, thanks.
Have you tried `:highlight Comment cterm=italic gui=italic` ?

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, check it out...
