### ISSUE TITLE
Indentation changed after comment

### ISSUE THREAD

**Issue by FMMS3** [rafi/vim-config#206]
Hi I met this prolem. If I comment any line using either "SPC+v" , "gc" or "gcc" then the indentation of any newlines will change. Previously tab size is 4 and after comment will change to 2. A simple fix is to reopen the file and everything is fine. Any idea on what cause this?

Cheers

**Comment by rafi** [comment]
And make sure to update plugins, `:call dein#update()`

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager, and using different plugins for comments. Check it out...
