### ISSUE TITLE
VimWiki Missing Commands

### ISSUE THREAD

**Issue by worldpe** [rafi/vim-config#208]
The only commands related to the vimwiki plugin that seem to work are VimwikiIndex & VimwikiUIselect, all of the other ones are seemingly missing, and I can't find any obvious reason why in the config file.

**Comment by rafi** [comment]
@worldpe the triggers to load Vimwiki are one of:
- <kbd>Leader</kbd>+<kbd>W</kbd>
- `:VimwikiIndex`
- `:VimwikiUISelect`

Once you run any _one_ of these, all the rest of Vimwiki's commands will be available from `:Vimwiki<Tab>`

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager.
Vimwiki isn't included in default setup, but it's included in `extras`. You can add it like this:

Paste this to `lua/plugins.lua` or `lua/plugins/<any name>.lua`:
```lua
return {
  { import = 'rafi.plugins.extras.org.vimwiki' },
}
```

You can also override key-mappings like this:

```lua
return {
  { import = 'rafi.plugins.extras.org.vimwiki' },
  {
    'vimwiki/vimwiki',
    keys = {
      { '<Leader>W', '<cmd>VimwikiIndex<CR>', { noremap = true } },
    },
  }
}
```
