### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by rafi** [rafi/vim-config#21]
Improve the README with latest plugins and key mappings.

**Comment by wsdjeg** [comment]
@rafi I want you to join SpaceVim, would you like to?

**Comment by wsdjeg** [comment]
ok, but I do not want to make spacevim as traditional distribution, but I want to make it as a platform, user can design their own layers.

**Comment by wsdjeg** [comment]
@rafi Hi, I just see you star space-vim, what do you think about it? and How about SpaceVim, What improvement should I make to get your approval。 😞
