### ISSUE TITLE
upgrade compe => cmp

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#210]
Hi @rafi 

Compe is becoming end of life. Any plans to upgrade from [compe](https://github.com/hrsh7th/nvim-compe) to [cmp](https://github.com/hrsh7th/nvim-cmp) ?

**Comment by rafi** [comment]
Hi @thecontinium. Pushed in latest commits.

**Comment by thecontinium** [comment]
cheers - I'll give it a spin :)
