### ISSUE TITLE
Theme Not Initialising Correctly

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#212]
After the latest changes there is no cursor highlight showing for fern.
I am using the default colour scheme of `hybrid`.

`:colorsheme hybrid` fixes this.

**Comment by thecontinium** [comment]
When nvim is opened the `UserSelectionBackground` is not set 

```
:highlight UserSelectionBackground
UserSelectionBackground xxx cleared
```

so on setting the CursorLine to this in fern_init we get no background for the cursor line.

@rafi are you seeing this or is it just my setup ?

cheers

**Comment by thecontinium** [comment]
Adding this to my local.vim was the only way I found to set the state correctly at startup.

`autocmd VimEnter * source /Users/thecontinium/.config/nvim/themes/hybrid.vim`

**Comment by thecontinium** [comment]
The problem is that `syntax enable` clears all the highlights so the auto command at the end of  

`config/init/dein#load_state(l:cache_path)`

``` vim
	autocmd user_events VimEnter *
		\ filetype plugin indent on
		\| syntax enable
```
clears highlights setup by the theme.
 
`syntax enable` needs to be before any colour schemes/themes are initialised.

**Comment by mm1ke** [comment]
I can confirm this issue. 
I have the exact same problem and the change in the `init.vim` fixed it for me (thx @thecontinium )

**Comment by ialiendeg** [comment]
I can also confirm the issue and the fix (thx @thecontinium )

**Comment by rafi** [comment]
I have been ill but better now :)  Thanks @thecontinium, disabled the autocmd

**Comment by thecontinium** [comment]
Good you are feeling better. Cheers
