### ISSUE TITLE
Telescope Lists doesn't allow item cycling without text

### ISSUE THREAD

**Issue by stonemaster** [rafi/vim-config#213]
First off, thanks a lot for the constant work on this and I really like the recent changes, in particular the switch to the telescope centric workflow! It's amazing, honestly!

One regression I found is that telescope windows like the Buffer overview (`; + b`) don't allow cycling the items with `Tab` or `Space + Tab` when the **input field is empty**. If you type at least one character, cycling becomes possible again.

I can reproduce that at least with the **Search history** and **Yank histroy** windows as well.

Is this an upstream issue or related to the NVIM configuration?

**Comment by rafi** [comment]
Hi @stonemaster. I'm not able to reproduce it, try updating all plugins, maybe your Telescope version is outdated?

**Comment by stonemaster** [comment]
Hi @rafi. Thanks for your response & the hint! I just updated my installation and indeed - the problem is gone. 

Sorry for noise!
