### ISSUE TITLE
JavaScript and HTML completion

### ISSUE THREAD

**Issue by VinukaThejana** [rafi/vim-config#216]
Hey, I am fairly new to JavaScript programming so when I link the javascript file to the HTML file and when I am editing the javascript file I can`t get completions like document.getElementById but if I do it via the HTML file by opening <script></script> then I can get the completion do you know the way to make this work.
Thanks in regards

**Comment by rafi** [comment]
Did you install the language-server?  Run `:LspInstall typescript`

**Comment by VinukaThejana** [comment]
It worked ,Thanks 😇
