### ISSUE TITLE
What is the highlighted section in the preview image

### ISSUE THREAD

**Issue by sansyrox** [rafi/vim-config#220]
Hi,

I really liked your vim config. I am also creating one of my own, would you mind telling me that what is the config shown in the right of the preview image? (Highlighted in red below) 
![687474703a2f2f726166692e696f2f7374617469632f696d672f70726f6a6563742f76696d2d636f6e6669672f66656174757265732e706e67](https://user-images.githubusercontent.com/29942790/137983517-cc11afef-b936-449d-b4fd-dd106609114f.png)

**Comment by rafi** [comment]
symbols-outline plugin. Open with <kbd>Space</kbd>+<kbd>o</kbd>
