### ISSUE TITLE
[Question] Some error message

### ISSUE THREAD

**Issue by Adnios** [rafi/vim-config#221]
After `make install`, it works well.

But when I try `:call dein#recache_runtime()`, there are some error messages as shown below.

![image](https://user-images.githubusercontent.com/41060790/138543981-c760afe2-c870-423a-aaba-767d9d5ce963.png)

Although there is some error, it still works. I just wonder why the error message occurs.

**Comment by rafi** [comment]
Lualine bugs have been fixed.
