### ISSUE TITLE
Cannot add TabNine properly

### ISSUE THREAD

**Issue by even-wei** [rafi/vim-config#222]
I'm trying to add an AI completions plugin https://www.tabnine.com/.
Since we are using `nvim-cmp`, I tried to setup TabNine with https://github.com/tzachar/cmp-tabnine#install.
I added `config/plugins.local.yaml`:
```
- repo: tzachar/cmp-tabnine
  on_source: nvim-cmp
  hook_post_update: './install.sh'
```

But got the message: `cmp-tabnine: Cannot find installed TabNine. Please run install.sh`

Did I miss anything?
Thanks!

**Comment by rafi** [comment]
@even-wei `hook_post_update` is for vim script, use `build`. See Dein's help `:h dein-options-build`
