### ISSUE TITLE
language server support for R and julia

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#223]
Hi Rafi

thanks once more for the great config! :-)

I have been trying unsuccessfully to add language server support for [R](https://www.rdocumentation.org/packages/languageserver/versions/0.3.11) and [julia](https://github.com/julia-vscode/LanguageServer.jl).

What would I need to do to register the language servers and to configure them?

Thanks!

**Comment by rafi** [comment]
Hi @kraxli. It seems nvim-lsp-installer has an open issue with Julia support: https://github.com/williamboman/nvim-lsp-installer/issues/143

You'll have to setup via nvim-lspconfig directly, see here: https://github.com/neovim/nvim-lspconfig/blob/1843c5fd9ae53ef3ffe3e67fc073fd870809b016/doc/server_configurations.md#julials

Good luck 🦾

**Comment by kraxli** [comment]
Thanks @rafi  for the reference!

**Comment by rafi** [comment]
@kraxli https://github.com/williamboman/nvim-lsp-installer added julials
