### ISSUE TITLE
Problem with binding using copilot

### ISSUE THREAD

**Issue by zsinx6** [rafi/vim-config#225]
I setup the config/plugins.local.yaml to add https://github.com/github/copilot.vim, the completions shows up but I'm unable to accept the suggestion using <Tab>. Also tried to disable some mappings with `let g:disable_mappings = 0` in config/local.vim, but also didn't work. I also tried to remove the https://github.com/hrsh7th/nvim-cmp, it worked but then every command throws errors about missing the plugin

**Comment by zsinx6** [comment]
Fixed changing the mapping in `lua/plugins/cmp.lua` for the <Tab>, I just used C-Tab instead

**Comment by rafi** [comment]
@zsinx6 Because copilot.vim uses <Tab> You can either:
- Remap copilot.vim's <tab> mapping, see `:h copilot#Accept()`
```vim
imap <silent><script><expr> <C-J> copilot#Accept("\<CR>")
let g:copilot_no_tab_map = v:true
```
- Try this nvim-cmp source plugin instead copilot.vim: https://github.com/hrsh7th/cmp-copilot
- Remap nvim-cmp's mappings, like you did.
