### ISSUE TITLE
I am getting TONS of errors now... 

### ISSUE THREAD

**Issue by kuttor** [rafi/vim-config#228]
Error detected while processing /Users/akuttor/.local/share/nvim/dein/repos/git
hub.com/rmagatti/session-lens/plugin/session-lens.vim:
line    6:
E5108: Error executing lua ...escope/_extensions/session-lens/session-lens-libr
ary.lua:2: module 'auto-session' not found:
        no field package.preload['auto-session']
        no file './auto-session.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2
.1.0-beta3/auto-session.lua'
        no file '/usr/local/share/lua/5.1/auto-session.lua'
        no file '/usr/local/share/lua/5.1/auto-session/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/
auto-session.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/
auto-session/init.lua'
        no file './auto-session.so'
        no file '/usr/local/lib/lua/5.1/auto-session.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/au
to-session.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by graysurf** [comment]
same problem

**Comment by alex-vy** [comment]
Since rmagatti/session-lens depends on rmagatti/auto-session, you should load that before session-lens. Fixed the errors for me.

**Comment by thecontinium** [comment]
me too

**Comment by sergiopatino** [comment]
![Uploading Screen Shot 2021-11-22 at 3.19.50 PM.png…]()

Hmm that did not work for me.

**Comment by sergiopatino** [comment]
Adding the depends seems to fix the error but it breaks LSP

**Comment by rafi** [comment]
What about latest 07aa8dea commit?

**Comment by sergiopatino** [comment]
still get the error unless I remove session-lens as a dependency. maybe some kind of circular dependency issue?

- repo: nvim-telescope/telescope.nvim
  if: has('nvim-0.5')
  depends: [ todo-comments.nvim, session-lens, telescope-zoxide ]
  on_cmd: Telescope
  on_lua: telescope
  hook_add: lua require('plugins.telescope').preload()
  hook_post_source: lua require('plugins.telescope').setup()

**Comment by sergiopatino** [comment]
latest commit resolved this for me.
