### ISSUE TITLE
Terminal freeezes when editing file in Cygwin

### ISSUE THREAD

**Issue by r2qokk** [rafi/vim-config#23]
I am using Cygwin 32/64-bit on Windows 10
`make test` is good.
Execute `vim` is fine.
However, when I try to edit any file, it freezes, even the initial buffer.
It is hard to tell from `vim -V`, because it seems to load lots of plug-ins at every input.

When I comment out https://github.com/rafi/vim-config/blob/master/config/vimrc#L63, things work fine, though, obviously, there is no plug-in.

**Comment by r2qokk** [comment]
turns out to be https://github.com/embear/vim-localvimrc/issues/43

**Comment by rafi** [comment]
Interesting. Thanks for reporting @r2qokk, I might add a condition to install it just on unix.

**Comment by r2qokk** [comment]
It should be symbolic link problem in https://github.com/embear/vim-localvimrc, since NTFS file system does not share the same behavior on symbolic link with UNIX world.
However, it would be great if you can detect this and make a switch onto the plug-in.
