### ISSUE TITLE
Lsp is not working

### ISSUE THREAD

**Issue by VinukaThejana** [rafi/vim-config#233]
recently I accidentally deleted the ~/.config/nvim directory and I recloned the repo after I recloned the repo none of the LSP's are working

when I run LspInfo I get 
```0 client(s) attached to this buffer```

**Comment by rafi** [comment]
Not sure which version you had. You can follow this to install LSP servers: https://github.com/rafi/vim-config#language-server-protocol-lsp
Or you can uses the UI of nvim-lsp-installer with `:LspInstallInfo`

**Comment by VinukaThejana** [comment]
Yeah I installed LSP`s as per the README but it is not working 
my neovim version is 0.7

**Comment by ialiendeg** [comment]
Maybe remove the `~/.local/share/nvim/lsp_servers` (or even the whole `~/.local/share/nvim`) and start again (this seems the same problem we commented recently in a commit thread).

**Comment by ialiendeg** [comment]
Maybe remove the `~/.local/share/nvim/lsp_servers` (or even the whole `~/.local/share/nvim`) and start again (this seems the same problem we commented recently in a commit thread).

**Comment by VinukaThejana** [comment]
yeah It is very strange It was working alright but I accidentally deleted the ~/.config/nvim folder and when I reinstalled it did not work
I removed every nvim folder and retried it 3 times the folders that I removed are
~/.local/share/nvim
~/.config/nvim
and even the cache folder of nvim

**Comment by ialiendeg** [comment]
Can you try what we said here? https://github.com/rafi/vim-config/commit/07aa8dea6719bab083b36ff99f82e1e2e647097b#commitcomment-61224827, because maybe our error is not fixed after all.

**Comment by VinukaThejana** [comment]
I will check it and let you know

**Comment by VinukaThejana** [comment]
removing depends: auto-session in config/pugins.yaml (line 3665) seems to fix the issue but I get lot of errors while opening vim how can I stop those errors

**Comment by VinukaThejana** [comment]
I kind of fixed the problem 
the version of my nvim is 0.7 so I changed every instance that said ```nvim-0.5``` to ```nvim-0.7``` in ```config/plugins.yaml```
so I think it did not load all the required modules as the nvim version is not 0.5

**Comment by ialiendeg** [comment]
Maybe you can try what Rafi says in https://github.com/rafi/vim-config/commit/07aa8dea6719bab083b36ff99f82e1e2e647097b#commitcomment-61647083

**Comment by VinukaThejana** [comment]
maybe but I think that was an issue with the version since the version was hardcoded

**Comment by rafi** [comment]
@VinukaThejana If you're using latest nvim HEAD, the version is now 0.7.0. There were a lot of changes in the LSP Lua API (see `:h deprecated`) https://www.reddit.com/r/neovim/comments/qd3v4h/comment/hhl1pbh/?utm_source=share&utm_medium=web2x&context=3

Latest commits a66484c9 and 7066da60 addresses the divergent api's on neovim 0.5.0 and >0.6.0. So you can now use both.

The `has('nvim-0.5')` is a check for 0.5 **or greater**. Try this: `:echo has('nvim-0.5')` and `echo has('nvim-0.7')`. If you have neovim 0.7.0 - both will return `1`, for true.
