### ISSUE TITLE
LSP stopped working

### ISSUE THREAD

**Issue by neowutran** [rafi/vim-config#235]
Recently, LSP stopped working. 

I believe it is an issue between how the "nvim-lspconfig" plugin and the "nvim-lsp-installer" plugin config work together. 
"nvim-lsp-installer" work: It is able to install LSP server
"nvim-lspconfig" work: It is able make all the LSP stuff available. 

Example of the issue, with a full updated "rafi/vim-config": 
- Open a rust file "main.rs". 
- Install the corresponding LSP server (``:LspInstall``)
- No LSP server is attached to the source file. Restarting neovim won't change that. 

If I try to manually attach it (``:lua require'lspconfig'.rust_analyzer.setup{}``, error message saying that the required binary (rust-analyzer) cannot be found. 

If I try to manually attach it and specify the exact binary path of the LSP server installed by "nvim-lsp-installer", then it work (``:lua require'lspconfig'.rust_analyzer.setup{cmd={"/home/ME/.local/share/nvim/lsp_servers/rust/rust-analyzer"}}``)

**Comment by rafi** [comment]
You can run `:LspInstallInfo` to get a nice UI with all LSP servers available, and installed.
Try uninstalling and reinstalling, and look in logs at `~/.cache/nvim`, specially `lsp.log`.

**Comment by TMTBO** [comment]
the same to me. The 'Congifured server list' got be empty.

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager.
