### ISSUE TITLE
plenary.log and plenary.path not found

### ISSUE THREAD

**Issue by d4em0n** [rafi/vim-config#239]
Hi, i got this following error when trying to `make`

![image](https://user-images.githubusercontent.com/29397847/149901192-c19b272f-375f-4b6f-9ed7-9aa4aa2ec46a.png)

![image](https://user-images.githubusercontent.com/29397847/149901296-17a50b7c-736b-4be9-9d1e-5b69bae8dfef.png)

Thanks,

**Comment by d4em0n** [comment]
This issue is gone apparently, this issue appear I was installing via WSL2 Ubuntu. But now I uninstall everything the WSL, and I reinstall in Ubuntu VM instead. I can't reproduced it again

**Comment by rafi** [comment]
Never tested this with WSL. It looks like a race-condition between plenary and dependant plugins.
Let me know if you find any more issues.

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, please test your issue and re-open if it still happens.
