### ISSUE TITLE
tinyline replaced?

### ISSUE THREAD

**Issue by sergiopatino** [rafi/vim-config#24]
Is tinyline still being used for status? I can't see where it's being loaded.

**Comment by rafi** [comment]
I have moved to a more simpler way of theming Vim, which is much more organized and composed in my opinion, you can see the statusline settings here: https://github.com/rafi/vim-config/blob/master/themes/rafi-2016.vim#L66

**Comment by sergiopatino** [comment]
thanks. that makes sense now.
