### ISSUE TITLE
Unknown function: badge#

### ISSUE THREAD

**Issue by crossgate10** [rafi/vim-config#242]
Hi, 
first, thanks for contributing this awesome config.
I have a question happened when I starting to using it.

I got this when I open some stuff file in nvim
![Screen Shot 2022-01-19 at 3 33 06 PM](https://user-images.githubusercontent.com/6496366/150085318-ff39fa8c-864f-4a01-a555-b74532728473.png)
how can I figure it out?

**Comment by rafi** [comment]
Hey, seems like I deleted badge.vim too soon, see latest push 7cbfbbbd

**Comment by crossgate10** [comment]
very thank you for revert it back :D

**Comment by rafi** [comment]
Totally forgot that the tabline still uses `badge.vim` and not `badge.lua`.
I'll refactor the tabline when I find some time soon.
