### ISSUE TITLE
Updating breaks everything

### ISSUE THREAD

**Issue by chrischen** [rafi/vim-config#247]
I just updated plugins by running "make" and it seems to break everything. It seems no plugins are installed/detected or something.

I get some errors during startup:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/109630/165644498-09ce2828-9fe6-4b1a-aa5a-e170feb6e953.png">

To reproduce, simply clone master and setup as new. Same errors happen that way.

Invoking find files:
`Not an editor command: Telescope find_files`

Spacebar doesn't bring up the context menu.

Would it be possible to integrate this into the "make update" process: https://github.com/Shougo/dein.vim/issues/353

Something like a "make rollback" if things break after installing.

**Comment by rafi** [comment]
Hi @chrischen, check latest 5ae35f30 commit.

**Comment by chrischen** [comment]
I did a fresh install, deleted .cache/vim/dein, and ran make.

<img width="965" alt="image" src="https://user-images.githubusercontent.com/109630/165854201-f3e7d7fa-9c88-431d-841c-5a04f858ec11.png">

And nothing seems to be working. Find files binding not working, and Fern not working.

**Comment by rafi** [comment]
@chrischen what version of Neovim are using?
Can you try running:
```
:call dein#recache_runtimepath()
```
And restart Neovim?

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, please test your issue and re-open if it still happens.
