### ISSUE TITLE
How do you use your current theme and how tabline open multiple tab pages？

### ISSUE THREAD

**Issue by yangqi766** [rafi/vim-config#249]
Your current VIM theme is modified based on hybrid. How can we use your theme？

The tab you define can only display the tabs of the current buffer. How to open multiple buffer tab pages, like bufferline nvim .

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager.
Please see README.md on how to disable tabstrip (tabline I'm using), and use something like bufferline.
Also, I've improved the tab/status line colors, so they will make an effort to adapt to any colorscheme.
