### ISSUE TITLE
config/local.vim does not appear to be honored

### ISSUE THREAD

**Issue by rpopp-fni-stl-com** [rafi/vim-config#252]
I rely heavily on expandtab and certain defaults for my shiftwidth/tabstop.

Per the README, I added a local.vim to ~/.config/nvim/config with the following contents:
set expandtab
set ts=4
set sw=4

However, if I try to edit any file afterwards (for example a perl script), none of those settings appear to be honored.  If I want those settings, I have to manually set them every time I open the editor.

Environment:  
nvim  version 0.8.0-dev compiled from source 
LuaJIT 2.1.0-beta3
ubuntu 18.04

Please advise

**Comment by rafi** [comment]
Hi @rpopp-fni-stl-com, it's not an issue with `config/local.vim`.  I'm using a plugin to autodetect these settings, called [vim-sleuth](https://github.com/tpope/vim-sleuth).

You can disable it by creating a `config/plugins.local.yaml` file and adding:
```yaml
- { repo: tpope/vim-sleuth, if: 0 }
```

This will overwrite the plugin settings (at `config/plugins.yaml`) and disable it. This is also where you can add your own plugins you want to use.

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager.
