### ISSUE TITLE
auto-session delete not working

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#254]
Adding `%*` to `wildignore` [here](https://github.com/rafi/vim-config/blob/5ae35f30ad478399d9b577e9cee62dcea14b3ec2/config/general.vim#L203) makes an error thrown when [deleting](https://github.com/rmagatti/auto-session/issues/138) with auto-session.

**Comment by rafi** [comment]
Thanks for reporting this. I removed the `wildignore` entries, they aren't really needed I guess.
