### ISSUE TITLE
Issue with Neovim and XDG config directory

### ISSUE THREAD

**Issue by niflostancu** [rafi/vim-config#26]
I've been using your config for the past months. 
I really like it, but there is an issue regarding its installation.

The README says you can install it by cloning into the .config/nvim directory (for **Neovim**):
```
git clone git://github.com/rafi/vim-config.git "${XDG_CONFIG_HOME:=$HOME/.config}/nvim"
```
But, in [config/vimrc#L14](/rafi/vim-config/blob/e19f2a82575e24378335e5c428a2bc668c387089/config/vimrc#L14), the path `$XDG_CONFIG_HOME.'/vim'` is hardcoded. Also note the use of the `$XDG_CONFIG_HOME` variable, which may be unpopulated on some distros (it should default to `~/.config`).

The same hardcoded path is also used at [config/init.vim#L34](/rafi/vim-config/blob/e19f2a82575e24378335e5c428a2bc668c387089/config/init.vim#L34), where you can see a comment which may suggest that the hardcoded path is deliberate:
```vim
" For Neovim, use .config/vim instead of .config/nvim
```
So where are you supposed to install the config for Neovim? If I install it to `~/.config/vim`, I must override the default vimrc using `nvim -u ~/.config/vim/vimrc`. If I want to install it to its official location, I must edit the hardcoded paths and replace `.config/vim` with `.config/nvim`.

Can you please update the scripts and add better autodetection (i.e. make both paths valid)? Also, don't forget to set default values for `XDG_*` variables.
Thanks.

Using Neovim **0.1.6** on Arch Linux, by the way.

**Comment by rafi** [comment]
Awesome, this helped get off my butt and improve it. Thanks for the details.
I ditched the XDG support for Vim and normalized installation into `~/.config/nvim` in README. 
Could you check the latest `master` commit eceaf6c3c1cda0de99cb6ebc2ac91e9d5ea59fcf ? It doesn't try to guess installation path.

**Comment by niflostancu** [comment]
That did it, thanks!
