### ISSUE TITLE
Update Registers Setup

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#264]
The setup for registers plugin has changed. The equivalent setup in the new style  is [here](https://github.com/thecontinium/vim-config/blob/53338ccb1c9f4a3bd99da38d441c68d41219d04f/config/local.plugins.yaml#L41) and [here](https://github.com/thecontinium/vim-config/blob/master/lua/local-plugins/registers.lua)

**Comment by alexpalyan** [comment]
I created a pull request for this: #273

**Comment by rafi** [comment]
fixed.
