### ISSUE TITLE
config doesn't want to load plugins

### ISSUE THREAD

**Issue by SolarAquarion** [rafi/vim-config#269]
[config/init] Unable to read configuration files at ['/home/solaraquarion/.vim/config/plugins.yaml']
Error detected while processing /home/solaraquarion/.vim/vimrc[1]../home/solaraquarion/.vim/config/vimrc[68]..function <SNR>4_source_file[5]..script /home/solaraquarion/.vim/config/init.vim[415]..function <SNR>5_main[49]..<SNR>5_use_dein[29]..<SNR>5_parse_config_files[11]../home/solaraquarion/.vim/vimrc[1]../home/solaraquarion/.vim/config/vimrc[68]..function <SNR>4_source_file[5]..script /home/solaraquarion/.vim/config/init.vim[415]..function <SNR>5_main[49]..<SNR>5_use_dein[29]..<SNR>5_parse_config_files:
line   10:
Vim(let):E712: Argument of extend() must be a List or Dictionary
Press ENTER or type command to continue

**Comment by rafi** [comment]
Make sure that your `/home/solaraquarion/.vim/config/plugins.yaml` YAML file is valid

**Comment by SolarAquarion** [comment]
You can see on my fork, I think my YAML config is valid?

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager.
