### ISSUE TITLE
problem with shebang

### ISSUE THREAD

**Issue by jlaunay** [rafi/vim-config#270]
Hello,
I want to add a shebang for bash files.
I added the following in the local.vim file:
```viml
augroup shebang
	autocmd!
	au BufNewFile *.sh,*.bash 0put=\"#!/bin/bash\<nl># -*- coding: UTF8 -*-\<nl>\<nl>\"|$
augroup END
```
When I create a new sh file, nothing is inserted.
The command `:messages` show 3 lines added but I have the following error which seems to interfere

`[null-ls] failed to run generator: ...ls.nvim/lua/null-ls/builtins/code_actions/shellcheck.lua:114: attempt to perform arithmetic on local 'match_row' (a nil value)`

Note, if I undo with `u` the shebang is added and using `VimEnter` instead of `BufNewfile` also works (but I want only for new files).

Is there a problem with my configuration?

**Comment by jlaunay** [comment]
I finally almost managed to fix the problem.
The problem is with the [`windo e` command](https://github.com/rafi/vim-config/blob/0b197c618abd451c6f65404ca551fa91b759da94/lua/plugins/lspconfig.lua#L181).
Someone familiar with Vim will most likely find a better solution but here is the hacky trick I used.

```lua
	-- Reload if files were supplied in command-line arguments
	if vim.fn.argc() > 0
		and vim.fn.has('vim_starting')
		and not vim.o.modified
		and vim.fn.line('w$') > 4
	then
		-- triggers the FileType autocmd that starts the servers
		vim.cmd('windo e')
	end
```

My shebangs are 3 lines  long so `and vim.fn.line('w$') > 4`  make vim reloading all buffer windows from disk only for file with more than 3 lines.

**Comment by rafi** [comment]
The issue seems to be an error from null-ls plugin which calls shellcheck binary and fails somewhere.

You can disable shellcheck or customize its settings in `lua/plugins/null-ls.lua`, look for `builtins.diagnostics.shellcheck`.

**Comment by jlaunay** [comment]
Thanks for your answer.
Could another method than `vim.cmd('windo e')` be used to start the server?
This way of launching the server causes strange behavior.
For example, I noticed that the autocommand SwapExists [here](https://github.com/rafi/vim-config/blob/7ae731386c2f1d19f86ad446b2146d672ab9b463/config/general.vim#L287) does not work because of this and raise the following error 
```
[dein] Error occurred while executing hook: nvim-lspconfig
[dein] Vim(lua):E5108: Error executing lua /home/jlaunay/.config/nvim/lua/plugins/lspconfig.lua:192: Vim(edit):E325: A
TTENTION
[dein] stack traceback:
[dein] ^I[C]: in function 'cmd'
[dein] ^I/home/jlaunay/.config/nvim/lua/plugins/lspconfig.lua:192: in function 'setup'
[dein] ^I[string ":lua"]:1: in main chunk
```

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, please test your issue and re-open if it still happens.
