### ISSUE TITLE
nvim-colorizer not active

### ISSUE THREAD

**Issue by jlaunay** [rafi/vim-config#271]
Hi,
I saw this config have 

```lua
- repo: norcalli/nvim-colorizer.lua
  if: has('nvim-0.4')
  on_event: FileType
  hook_post_source: lua require('plugins.colorizer')
```
  
When I open a file with hex colors the plugin does not seem active.

In order to make it work I have to either change `hook_post_source` to `hook_source` or add the following:

```viml
autocmd VimEnter * call dein#call_hook('post_source')
```

Is this the normal behavior?
What is the correct config?

Thanks for your help

**Comment by rafi** [comment]
Pushed a whole new rewrite of vim-config, I've replaced nvim-colorizer plugin.
