### ISSUE TITLE
comittia plugin configuration changes potentially broken

### ISSUE THREAD

**Issue by eikel** [rafi/vim-config#272]
I am using the `master` branch of your configuration with neovim. It seems that commit 24c1dded17bcb9f5ef087b659650aea82ae523ec broke [committia](https://github.com/rhysd/committia.vim) for me.

Calling `git commit` on current `master`:
![broken](https://user-images.githubusercontent.com/1190698/201036069-7d2e36b2-b625-4b1d-8afb-cdddc604ac33.png)
Please note that the diff and status windows are empty and the diff window on the right is the active one, instead of the commit message window in the top left.

Calling `git commit` after reverting the mentioned commit:
![fixed](https://user-images.githubusercontent.com/1190698/201035814-10c649b9-dddf-48ff-871b-09c3d99c0168.png)

**Comment by stonemaster** [comment]
I can confirm that reverting this commit works for me as well (my plugin was broken for some time too). I am on `neovim` and Ubuntu.

**Comment by rafi** [comment]
Fixed committia's auto-loading, and trigger it only when vim is starting.
