### ISSUE TITLE
Vimwiki and Zk workflow

### ISSUE THREAD

**Issue by DancingQuanta** [rafi/vim-config#275]
What is your workflow for Vimwiki and Zk?

Do you use both for the same wiki and separately?

**Comment by rafi** [comment]
I abandoned Vimwiki in-favor of Zk and its awesome LSP features.
Pushed a whole new rewrite of vim-config, 100% lua and lazy.nvim as package-manager,
and vimwiki has been downgraded to `extras`. (Not included by default)
