### ISSUE TITLE
neo-tree dockerfile icon show

### ISSUE THREAD

**Issue by ghost** [rafi/vim-config#283]
![image](https://user-images.githubusercontent.com/13087771/231706903-2f447639-3819-4777-89cb-5657ef2a1e32.png)

new version vim-config show dockerfile this effect on the neo-tree

**Comment by rafi** [comment]
Which font are you using?
The icons unicode is returned from https://github.com/nvim-tree/nvim-web-devicons
Maybe you're using an outdated nerdfont?

**Comment by rafi** [comment]
Update your nerdfont to v3+, see [v3.0.0 breaking changes](https://www.nerdfonts.com/releases)
Use [nerdfix](https://github.com/loichyan/nerdfix) to locate deprecated codes.
