### ISSUE TITLE
choose window not work

### ISSUE THREAD

**Issue by TMTBO** [rafi/vim-config#284]
Can not choose the window with `sp` and `sw`

**Comment by rafi** [comment]
Do you have more than two windows in the tabpage?

**Comment by TMTBO** [comment]
Yes I have. Actually, I got the winbar shows on the window

**Comment by rafi** [comment]
The nvim-window-picker plugin changed quite a bit recently, try again after updating. You should now see large hint letter (see screenshot).
![image](https://github.com/rafi/vim-config/assets/147918/d7474a41-0725-4c36-b08a-f3761215576e)

**Comment by TMTBO** [comment]
Yes, it works now. thx
