### ISSUE TITLE
The plugins NOT installed which under `extras` folders

### ISSUE THREAD

**Issue by TMTBO** [rafi/vim-config#285]
The plugins NOT installed which under `extras` folders. Such as `Copilot`.
And It installed correctly when I move `copilot.lua` to `lua/rafi/plugins/copilot.lua`.
![image](https://user-images.githubusercontent.com/2801001/234483821-fedc794e-d0db-4cb0-bb5b-9e24d58c729a.png)

**Comment by rafi** [comment]
If you are using this repo as-is, create a file named `lua/plugins.lua` or `lua/plugins/<whatever>.lua` and place any plugins you want there. For example:
```lua
return {
	-- Extras
	{ import = 'rafi.plugins.extras.ui.incline' },
	{ import = 'rafi.plugins.extras.coding.copilot' },

	-- From GitHub
	{
		'glepnir/flybuf.nvim',
		cmd = 'FlyBuf',
		keys = {
			{ '<Leader><Tab>', function() require('flybuf').toggle() end, desc = 'Flybuf' }
		},
		config = true
	},
}
```

**Comment by TMTBO** [comment]
thanks, it works!
