### ISSUE TITLE
Allow lazy setup to be configurable

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#286]
I don't think this is possible now ?

It would be useful to be able to configure the setup of lazy that is done [here](https://github.com/rafi/vim-config/blob/53feb90f0dd64cf115dcd045bee7c7be55166574/init.lua#L19)

cheers

**Comment by rafi** [comment]
Added in latest master. thanks 👍

**Comment by thecontinium** [comment]
Great. Works for me. Thanks.

--
The Continium

On 28 April 2023 at 19:47:30, Rafael Bodill ***@***.******@***.***>) wrote:

Added in latest master. thanks 👍
