### ISSUE TITLE
E117: Unknown function

### ISSUE THREAD

**Issue by tpanetti** [rafi/vim-config#29]
make test passes fine, but running make crashes. Here's my error 
```
Error detected while processing /home/tpanetti/.config/nvim/config/vimrc:
line   83:
Vim(python):E117: Unknown function: provider#python#Call
Press ENTER or type command to continue
```
My OS is Arch

**Comment by rafi** [comment]
You will need python3, have you got that installed?
Can you rename `~/.config/nvim` to `~/.config/nvim.bak` or something, and run `nvim` and then `:CheckHealth` - this will run health checks on your Neovim installation.

**Comment by rafi** [comment]
Any success?

**Comment by rafi** [comment]
No response, closing.
