### ISSUE TITLE
How do I handle large files?

### ISSUE THREAD

**Issue by whxcode** [rafi/vim-config#294]
hi Rafael.

I like this configuration very much, but occasionally I edit some large files (5M~10M), but when I use nvim to open it, the program will freeze. How can I fix this error?

**Comment by rafi** [comment]
Have you tried disabling Treesitter on large file? does that help?
If it does, you can disable it automatically, but adding following to treesitter `opts`:
```lua
			highlight = {
				enable = true,
				disable = function(_, buf)
					local max_filesize = 100 * 1024 -- 100 KB
					local ok, stats = pcall(vim.uv.fs_stat, vim.api.nvim_buf_get_name(buf))
					if ok and stats and stats.size > max_filesize then
						return true
					end
				end,
			},
```

This plugin https://github.com/LunarVim/bigfile.nvim claims to help in this area.

Also this Neovim patch should improve things I guess: https://github.com/neovim/neovim/pull/26827

**Comment by rafi** [comment]
Adopted LazyVim's autocmds that shutdown treesitter/syntax on large files. See 9c8e28f4
