### ISSUE TITLE
Error after loading any LSP

### ISSUE THREAD

**Issue by SmartassSkeleton** [rafi/vim-config#295]
Hey @rafi,

After a Lazy update, I started getting errors anytime I open a file and an LSP is attached:

```bash
Error detected while processing LspAttach Autocommands for "*":
Error executing lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        /home/smartassskeleton/.config/nvim/lua/rafi/plugins/lsp/keymaps.lua:133: in function 'on_attach'
        /home/smartassskeleton/.config/nvim/lua/rafi/plugins/lsp/init.lua:104: in function 'on_attach'
        /home/smartassskeleton/.config/nvim/lua/rafi/lib/utils.lua:18: in function </home/smartassskeleton/.config/nvim/lua/rafi/lib/utils.lua:14>
        [C]: in function 'nvim_exec_autocmds'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1530: in function '_on_attach'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1357: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by thecontinium** [comment]
I have the same problem.

**Comment by whxcode** [comment]
I have the same problem.

**Comment by whxcode** [comment]
> Hey @rafi,
> 
> After a Lazy update, I started getting errors anytime I open a file and an LSP is attached:
> 
> ```shell
> Error detected while processing LspAttach Autocommands for "*":
> Error executing lua callback: vim/keymap.lua:0: rhs: expected string|function, got nil
> stack traceback:
>         [C]: in function 'error'
>         vim/shared.lua: in function 'validate'
>         vim/keymap.lua: in function 'set'
>         /home/smartassskeleton/.config/nvim/lua/rafi/plugins/lsp/keymaps.lua:133: in function 'on_attach'
>         /home/smartassskeleton/.config/nvim/lua/rafi/plugins/lsp/init.lua:104: in function 'on_attach'
>         /home/smartassskeleton/.config/nvim/lua/rafi/lib/utils.lua:18: in function </home/smartassskeleton/.config/nvim/lua/rafi/lib/utils.lua:14>
>         [C]: in function 'nvim_exec_autocmds'
>         /usr/share/nvim/runtime/lua/vim/lsp.lua:1530: in function '_on_attach'
>         /usr/share/nvim/runtime/lua/vim/lsp.lua:1357: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> ```
It seems to be caused by updating lazy.nvim.

**Comment by thecontinium** [comment]
I think this fixes it https://github.com/rafi/vim-config/pulls
