### ISSUE TITLE
LazyExtras not persisted after install

### ISSUE THREAD

**Issue by SmartassSkeleton** [rafi/vim-config#299]
The LazyExtras section in super cool! I'd like to enable some of the extras there.

The `:LazyExtras` window does open and I am able to enable any plugin I want using `x`. The notification window in the top right says I should restart LazyVim for the changes to take effect.

After I restart NeoVim (I'm not aware of a way to just restart LazyVim without closing and opening NeoVim again) and I `:LazyExtras` all the extras I've enabled are in the disabled list.

Am  I missing something?

**Comment by flamedmg** [comment]
Having same issue like you. Did you find a solution for it?

**Comment by rafi** [comment]
Can you guys update with latest `master` and try again?

**Comment by flamedmg** [comment]
Cloned master, cleaned all caches, executed, waited till lazy did it stuff. Restarted and selected few random records with `x` - restarted neovim as suggested - no luck, nothing is selected or installed during startup

**Comment by flamedmg** [comment]
@rafi it looks like https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/xtras.lua is missing. When i added it to the `lua/rafi/puginx/xtras.lua` it works now

**Comment by SmartassSkeleton** [comment]
I can confirm that @flamedmg's solution solved it for me.

**Comment by rafi** [comment]
This has been fixed at c09d0fb
