### ISSUE TITLE
Weird characters in html page

### ISSUE THREAD

**Issue by vakosel** [rafi/vim-config#3]
Hi again .
i opened a test html file , plain one i typed html5 and chose the snippet , saved it and opened in browser
this is the source code of Crhome (archlinux)

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title><`2`></title>
  </head>
  <body>
    <`3`>
  </body>
</html>
What i saw in vim when i saved the file was nothing between body and title. Why is this happening with
these <'2'> <'3'> ?
I tried to wrote something in between but these characters persisted .
Any idea?
I haven't changed anything in your configuration.

**Comment by vakosel** [comment]
Did not paste source code .try again
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title><`2`></title>
  </head>
  <body>
    <`3`>
  </body>
</html>

**Comment by vakosel** [comment]
Anyw

**Comment by vakosel** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title><`2`></title>
  </head>
  <body>
    <`3`>
  </body>
</html>

**Comment by vakosel** [comment]
<title><`2`></title>
  </head>
  <body>
    <`3`>
  </body>

**Comment by vakosel** [comment]
I can't paste it here .so this is the result
http://pastebin.com/ePj0djsa
any idea?

**Comment by rafi** [comment]
This is a feature of [neosnippet](https://github.com/Shougo/neosnippet.vim).
After you selected the snippet - make sure to press Tab a few times to jump to edit points.
You can remove all the markers as soon as you leave Insert mode, as specified in the docs [here](https://github.com/Shougo/neosnippet.vim/blob/master/doc/neosnippet.txt#L762-L765).

**Comment by vakosel** [comment]
thanks again and a last question .If i want to use snippets for both php and html
can i use : set filetype=php.html
Thanks in advance

**Comment by rafi** [comment]
Neosnippet might be using [context_filetype.vim](https://github.com/Shougo/context_filetype.vim), but I'm not sure. If it does, it can detect other languages within a file without the need to `set filetype`. The question is more appropriate at the plugin in question, [neosnippet](https://github.com/Shougo/neosnippet.vim)
