### ISSUE TITLE
python folding

### ISSUE THREAD

**Issue by sergiopatino** [rafi/vim-config#30]
just curious of folding works properly for you on python files. doesn't seem to using your config. always folds at the highest defined method. 

something like https://github.com/tmhedberg/SimpylFold might be a better option than using the indent foldmethod.

**Comment by rafi** [comment]
I'm not much of a folding guy, I should use them more actually. I'll try SimplyIFold, thanks.

This is how a folded python file looks for me after pressing `zM`:
![image](https://cloud.githubusercontent.com/assets/147918/24189174/aa07dae4-0eec-11e7-9b9e-713350e49711.png)

**Comment by rafi** [comment]
Added SimpylFold and FastFold

**Comment by sergiopatino** [comment]
thumbs up!
