### ISSUE TITLE
consider adding a ruby yaml2json

### ISSUE THREAD

**Issue by aeruder** [rafi/vim-config#32]
I know this config largely is based around python, but a few points in favor of ruby:

- It is often installed
- Both YAML and JSON decoders are builtin since 1.9.something

This may be a good fallback (or even default) when ruby is detected in the path.  Here's a working yaml2json that reads from stdin and writes to stdout.

    #!/usr/bin/env ruby
    require 'yaml'
    require 'json'

    print JSON.generate YAML.load $stdin.read

This requires a stock ruby install only.

**Comment by rafi** [comment]
It's not specifically for Python, but lacks good Ruby support.
Sounds like a good alternative for python+PyYAML..
Would you be able to modify [config/vimrc](https://github.com/rafi/vim-config/blob/master/config/vimrc#L23) and include this bit?
