### ISSUE TITLE
Not able to install SuperTab

### ISSUE THREAD

**Issue by rith-iqlect** [rafi/vim-config#35]
Rafi, first of all! Thank you! This is one of the amazing vim-configs I have experimented with
How to install SuperTab with correct rules in the plugins.yaml? I get this error when I simply do
 - repo: ervandew/supertab 
  E475: Invalid argument: pumvisible() ? "\<Up>" : "\<C-H>"

Could you please suggest the correct configuration for it?

**Comment by rafi** [comment]
Hi, thanks for your good word :) I'm happy it's useful to others as-well.
You will need to disable the Deoplete keyboard mappings, you can find them here:
https://github.com/rafi/vim-config/blob/master/config/plugins/deoplete.vim#L116-L153

These keyboard-shortcuts are set to work with Deoplete and probably collide with SuperTab.. You should ask for help in the Deoplete project if you're trying to integrate both.. good luck.

**Comment by rafi** [comment]
Have you been able to disable deoplete successfully?

**Comment by rafi** [comment]
Hope this helped.
