### ISSUE TITLE
No colors in terminator/Gnome-Terminal

### ISSUE THREAD

**Issue by rith-iqlect** [rafi/vim-config#36]
Rafi,
Your config works for xterm flawlessly with great colors. However, I was not able to make it work for 
Gnome-terminal or Terminator in Ubuntu 14.04/16.04

For Terminator(Gnome-Terminal): I did  :set guicursor=  to get rid of weird characters. 
But I don't get any colors (i.e syntax highlighting at all). It's always white text on black background.
This is really not a nvim problem per se. 
If I used any init.vim with nvim, I get syntax highlighting and colors but not with you config.
What could have been the issue?

Thank you!

**Comment by rafi** [comment]
Hi. Could you try to disable the `termguicolors` from https://github.com/rafi/vim-config/blob/master/config/theme.vim#L10 and try again?

**Comment by rith-iqlect** [comment]
Wow! It solved the issue! Thanks so much!  :-)

**Comment by rafi** [comment]
Great! Could you tell me what's your `TERM` value?  (i.e. `echo $TERM`), and are you running inside Tmux?

**Comment by rith-iqlect** [comment]
Rafi,
It's xterm-256color

**Comment by rith-iqlect** [comment]
I'm not running inside tmux when using Gnome-terminal.  Here are the final observations.
1. Works flawlessly  in xterm
2. xterm + tmux : not great experience, different rendition of colors + vim command bar is not visible. 
3. Gnome -Terminal, wasn't working fine.  But after commenting out termguicolors, it's flawless now.

**Comment by rafi** [comment]
Thanks for the report. I'll try to improve the terminal detection.. :)
