### ISSUE TITLE
Auto completion; xterm vs gnome-terminal

### ISSUE THREAD

**Issue by rith-iqlect** [rafi/vim-config#37]
Rafi,
I attach two images of autocompletion for python with your config. one is in xterm and the other is in gnome-terminal.
In gnome-terminal, there are weird characters popping up. Do you know how to fix this?

Thank you

![xterm raficonfig](https://user-images.githubusercontent.com/20392829/28324368-cf34b12a-6bf8-11e7-89bc-cd50ec54f7d1.png)
![terminal raficonfig](https://user-images.githubusercontent.com/20392829/28324378-d3347454-6bf8-11e7-8db3-fb07cceb7c7d.png)

**Comment by rafi** [comment]
Also deoplete configuration [here](https://github.com/rafi/vim-config/blob/master/config/plugins/deoplete.vim#L69-L78)

**Comment by rafi** [comment]
Hi @rith-iqlect,

These are the marks I'm setting in [here](https://github.com/rafi/vim-config/blob/master/config/plugins/deoplete.vim#L85-L98)
Could you comment out these lines and try again?

**Comment by rafi** [comment]
Hope this helped.
