### ISSUE TITLE
command to past a pattern to the end of the line is not working correctly

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#39]
Hi Rafi,

thanks for your great config! 
One issue I have with it, is that the following mapping to paste a pattern to the end of the line does not paste the pattern to the end of the line but to the beginning of the next line.
```
noremap <leader>td $ "=strftime(" @DONE: %Y-%m-%d")<CR>P 
```
So far this mapping worked as expected but not with your configuration. Do you know which setting (or what else) may cause this? 

Many thanks
David

**Comment by rafi** [comment]
Hi, try without the space between `$` and `"`, i.e.:
```
noremap <leader>td $"=strftime(" @DONE: %Y-%m-%d")<CR>P
```

**Comment by kraxli** [comment]
Many thanks :-)
```
noremap <leader>td $"=strftime(" @DONE: %Y-%m-%d")<CR>p
```
works perfectly! Still which is the option that lets the cursor jump from the end of a line to the beginning of the next line? (Its kind of hard to google for that)

**Comment by rafi** [comment]
I guess it's the space that messed things up, in my config space is the <Leader> key..

**Comment by kraxli** [comment]
Thanks for your help and your config Rafi!
