### ISSUE TITLE
Colorschemes

### ISSUE THREAD

**Issue by VincentBurke** [rafi/vim-config#41]
Trying to change this setup to the nord vim colorscheme(https://github.com/arcticicestudio/nord-vim). Colorscheme works but every time i open vim it says:
```
Error detected while processing /Users/vincent/.config/nvim/config/theme.vim:
line   31:
E185: Cannot find color scheme 'nord'
Press ENTER or type command to continue
```

To install I copied [this file](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim) over to the themes folder. I then edited config/theme.vim and changed `let g:theme_name = 'rafi-2017'` to `let g:theme_name = 'nord'`
Thanks in advance!

**Comment by PegasusWang** [comment]
`:colorscheme solarized8_dark`, like this, but it should in repo: rafi/awesome-vim-colorschemes

**Comment by rafi** [comment]
Hi @VincentBurke, you don't need to change `g:theme_name`. Changing `g:theme_name` means the `themes/` loading will be different. Make sure this theme exists there. Leave it at the default `rafi-2017` probably...

I have added `nord` colorscheme to [rafi/awesome-vim-colorschemes](https://github.com/rafi/awesome-vim-colorschemes), the plugin I'm using for the collection of colorschemes. Make sure you upgrade this plugin and you'll have the `nord` color-scheme.
