### ISSUE TITLE
Executable `yaml2json` is ambiguous

### ISSUE THREAD

**Issue by roschaefer** [rafi/vim-config#44]
That could be anything, e.g. I'm using archlinux and I had [`haskell-yaml`](https://www.archlinux.org/packages/community/x86_64/haskell-yaml/) installed  which [comes with a `yaml2json` executable](https://www.archlinux.org/packages/community/x86_64/haskell-yaml/files/).

Removing that from my system helped to resolve an error during `make install`.

**Comment by rafi** [comment]
Hi. I merged #46 which should fix this, let me know.

**Comment by roschaefer** [comment]
1. `sudo pacman -S haskell-yaml` (reinstall haskell-yaml)
2. `cd .config/nvim`
3. `git clone`
4. `make install`
5. No errors so far -- seems to be alright :+1: 

Closing.
