### ISSUE TITLE
Reaching for an Escape

### ISSUE THREAD

**Issue by Greg-Johns** [rafi/vim-config#48]
Just curious why you removed `imap j; <Esc>` from mappings?

**Comment by rafi** [comment]
Are you sure I had a `j;` mapping? you remember which commit?

**Comment by Greg-Johns** [comment]
I looked around the logs but couldn't find it, just asking to see if you took it out due to some key conflict. I might have added to my local and forgot about it. Thanks for the response though and sharing your config ;)

**Comment by rafi** [comment]
I don't remember an insert `j;` mapping, but I do remember `jk`. I removed it because I didn't use it. I map my Caps-lock to Escape & Shift.
