### ISSUE TITLE
Highlight problem

### ISSUE THREAD

**Issue by vakosel** [rafi/vim-config#5]
Hi !
I have a problem and i can't solve it. When i open a file i.e.     ~/.Xresources or general.vim or whatever i need to save the file in order to highlight the syntax . Strange isn't it . I have not changed anything from your configuration. I tried syntax on and then it throws error

Error detected while processing function choosewin#color#refresh
E716 key not presen in DIctionary: gui
E15 Invalid expression: a:color[s::Screen] 
etc..

I renamed choosewin  and then no error but no highlight too.. Only when saving the file
Any idea??
Thanks in advance, 
Kostas

PS ArchLinux os  . It worked a couple of months ago. rxvt-unicode (it does it in other xfce-terminal too)

**Comment by vakosel** [comment]
Also when i start vim with -u NONE or -u NORC no highlight of course but syntax on works perfectly . No errors and syntax is highlighted . 
I hope you can help me . The only change i did recently ( before it worked ) is that i changed lightdm display manager with gdm . I only mention that.
Looking forward for you help 
vakosel

**Comment by rafi** [comment]
Hi! 
Hope this [commit](https://github.com/rafi/vim-config/commit/d58c6a7f53be5ac62dc7ff59675c679d37c93b19) fixes it.

**Comment by vakosel** [comment]
excellent as usual !
Thanks bro!
