### ISSUE TITLE
completion config for other languages

### ISSUE THREAD

**Issue by marcote** [rafi/vim-config#52]
Hi rafi

First, let me thank you for this awesome vim config.

I've been trying to enable completion for go language without luck and I wonder what needs to be done to enable go lang (and other languages, let's say elm or typescript) using this configuration. 

Depending how complex (or doable) is it, I would like to contribute a small piece into the readme, but first I need some pointers

Thank you!

**Comment by marcote** [comment]
Golang completion works :) still curious about setting up other languages.

Thank you

**Comment by rafi** [comment]
Glad you're enjoying it.
You can check out [deoplete](https://github.com/Shougo/deoplete.nvim)'s documentation, my configuration uses it as a central engine for code completion. Notice the [external sources](https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L1109) section in docs where you can find extensions for other languages.
