### ISSUE TITLE
option to display full html-path and math when on line

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#56]
Hi 
thanks again for your nice settings what really eases the work with vim :-) 

How can I display (expand) a full html-path/math when the cursor is on the line with the path?

Current view:
```
some text ... https://github.com/~/vim-config ... more text
```
Wished view:
```
some text ... https://github.com/rafi/vim-config  ... more text
```
I can see (expand) the path/math in the visual mode but this not practical for editing.

**Comment by rafi** [comment]
@kraxli which state & view are you referring to? Can you include a screenshot?

**Comment by kraxli** [comment]
sure and many thanks for coming back on this! 

It is an example from a vimwiki file. 

What I see is the first image:
![screenshot from 2018-01-05 22-00-50](https://user-images.githubusercontent.com/8371948/34628268-09a8177e-f264-11e7-9b71-8a79f618da09.png)

What I would love to see for editing when the cursor is on the line (in the insert mode) is:
![screenshot from 2018-01-05 22-02-44](https://user-images.githubusercontent.com/8371948/34628340-30e62f1a-f264-11e7-8139-dac6ef3f5e3b.png)
Here I got this view by highlighting the section what is not really practical for editing.

**Comment by rafi** [comment]
You should ask about this in [vimwiki/vimwiki](https://github.com/vimwiki/vimwiki). From a quick-look at their [docs](https://github.com/vimwiki/vimwiki/blob/dev/doc/vimwiki.txt#L2722), I see you need to set the `g:vimwiki_conceallevel` variable, which is `2` by default.

**Comment by kraxli** [comment]
Great - thanks! I wasn't aware that this is under the conceal settings. In config/gerneral.vim file there is 
```
set conceallevel=2 concealcursor=niv
```
setting the concealcursor to 
```
set  concealcursor=nv
```
does exactly what I was looking for :-)

Many thanks!
