### ISSUE TITLE
how to add custom plugin and settings so I can safely pull in case of update? 

### ISSUE THREAD

**Issue by robgrzel** [rafi/vim-config#58]
Hi! This vim distro is AWESOME! Others are so so when compared! Simply godly job young man!
 
I want to add llgb and gdb vim plugins, etc... but I would like them to be separated from original config. 
Also some nmapings for this plugins in "vimrc". 

Should I just fork it and change as please?

**Comment by rafi** [comment]
Hi Robert, thank you for the compliments, I use it everyday and enjoy it too :)

You can create a `.vault.vim` file in the root of the configuration, and add Vim configuration.
For plugins, I really should create a local YAML, but haven't done this yet.

I suggest simply cloning the repo and run `git pull` from time to time, if you're going to make small changes, I don't expect any conflicts.

**Comment by rafi** [comment]
I've added a special loader for `config/local.vim`, if exists. Pull the changes from repository and create this file and add your custom settings. Enjoy!

**Comment by subwindow** [comment]
I'm a little confused. Am I supposed to add new plugins to `config/plugins.yaml`? Or should I add them to my `config/local.vim` in the dein style of `call dein#add('user/repo')`?

**Comment by shafiquejamal** [comment]
@rafi : could you provide a sample `config/local.vim` file and instructions on how to update nvim to include custom plugins? Thanks!

**Comment by rafi** [comment]
@subwindow @shafiquejamal checkout pull request #62 for a custom way of adding plugins.
