### ISSUE TITLE
why this theme its so lagging? 

### ISSUE THREAD

**Issue by robgrzel** [rafi/vim-config#59]
When I open vim on windows wsl-terminal, it indeed looks great, this theme. But when I scroll or pgdown its lagging.  When I open in with normal windows wsl bash, its much faster, but then I can see that during scrolling, right side of each word gets dark. Is it due to rerendering so much?

**Comment by robgrzel** [comment]
I add onedark theme, now its working fine :)

**Comment by rafi** [comment]
I haven't tested it with Windows, so unfortunately I'm not sure what's the different between wsl-terminal and wsl-bash.

You can try different colorschemes with typing `:colorscheme ` and press Tab after a space, you'll see many nice colorschemes you can test on.

**Comment by robgrzel** [comment]
wsl-terminal let me have 256 colors, in bash I would have to set myself

**Comment by rafi** [comment]
Any update?
