### ISSUE TITLE
neobundleinstall download uses svn

### ISSUE THREAD

**Issue by vivekiitkgp** [rafi/vim-config#6]
This may not work out of the box for every user (proxy setup!). I feel that using `git` download by default would be a good idea (if it's possible to set it somewhere in your setup).

**Comment by rafi** [comment]
Hi Vivek, I haven't quite understood the issue.
I have NeoBundle to use git by default here: [config/init.vim#L39](https://github.com/rafi/vim-config/blob/f2a58b7aa84f45afa0190fe96a70eff4f5f235e7/config/init.vim#L39)

**Comment by vivekiitkgp** [comment]
Weird. I had to setup `svn` to be able to use it. Also, after the installation was complete, when I open vim, I get the following message repeated several times.

`[neobundle] The protocol "git"is invalid.  Please use https or ssh instead.`

**Comment by vivekiitkgp** [comment]
Also, changing theme using `color atom` for example spews a lot of errors.

**Comment by rafi** [comment]
That's weird. Have you added a plugin which might be version-controlled with SVN?
About the theme, the proper command is `colorscheme atom`

**Comment by vivekiitkgp** [comment]
> Have you added a plugin which might be version-controlled with SVN?

Nope. Straight out of the box install.

> proper command is colorscheme atom

Same behavior.

**Comment by rafi** [comment]
The `git` protocol uses a different port I think.

**Comment by rafi** [comment]
Neobundle [removed](https://github.com/Shougo/neobundle.vim/commit/c2ac00894734e9cd3da53f676582f08b51903cf5) `git` protocol support. I [removed](https://github.com/rafi/vim-config/commit/70b763fb1e766ebcc9bef8c666298b2d9ed43998#diff-62054c16147565beb3c4d6118c18ab9fL39) my setting, so it defaults on `https` now. Thanks for reporting!

**Comment by vivekiitkgp** [comment]
@rafi The `colorscheme` issue seems to be caused by `choosewin` plugin. Removing it fixed the problem.

**Comment by rafi** [comment]
@vivekiitkgp Could you open a new issue about `colorscheme`+`choosewin` with the errors you mentioned before? Thanks!
