### ISSUE TITLE
Hide vertical line

### ISSUE THREAD

**Issue by d4em0n** [rafi/vim-config#60]
Hi!, thanks for great vimrc. this is awesome vim config, good job bro
i got a little problem, the vertical line appear on center my screen. Can i hide the vertical line ? how ?

![neovim](https://user-images.githubusercontent.com/29397847/35107524-321e484c-fc3f-11e7-83d4-d854ebc2ff9a.png)

**Comment by d4em0n** [comment]
Problem solved using command `:set colorcolumn=`. i want disable colorcolumn everytime i open neovim. but i don't know where i place that command without conflicting repository. i put that command in .vault.vim, it does no effect, because .vault.vim is executed before [config/general.vim](https://github.com/rafi/vim-config/blob/b376976ce36c23d7c3c3503623fd5e95d425f625/config/general.vim#L168).

**Comment by rafi** [comment]
Hi @d4em0n, I've added a special loader for `config/local.vim`, if exists. Pull the changes from repository and create this file and add your custom settings. Enjoy!

**Comment by d4em0n** [comment]
Thanks for your reply. Now i can set my own configuration.
