### ISSUE TITLE
virtualenv2/3: command not found & .cache/vim/venv/neovim3/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by valh1996** [rafi/vim-config#61]
Hi,

i got these errors when i execute venv.sh :

> MacBook-Pro-de-Valentin:nvim valh$ ./venv.sh
> ./venv.sh: line 14: virtualenv2: command not found
> ./venv.sh: line 15: virtualenv3: command not found
> PYTHON 2
> ./venv.sh: line 19: /Users/valh/.cache/vim/venv/neovim2/bin/pip: No such file or directory
> PYTHON 3
> ./venv.sh: line 21: /Users/valh/.cache/vim/venv/neovim3/bin/pip: No such file or directory

I have however python2/3 installed with pip3 and virtualenv2/3

Do you have any idea ?

Thank you

**Comment by korlaxxalrok** [comment]
I have the same issue on MacOS. I've installed `virtualenv` as prescribed in the install instructions.

I think the script is forcefully setting the executable used to create the venvs to `virtualenv-2.7` and `virtualenv-3.6` which does not work across the board. pip2/3 seems to install a single executable. Probably something can be done to more accurately find the executable for `virtualenv` across different systems and package managers.

On my system, I can run `hash | grep virtualenv` to find the executable, which is `/usr/local/bin/virtualenv`.

A quick work around adjustment to the script, once you find the executable(s) you need to use, might look like this (easier, even, if the executable is in your path):
```
# Try to detect virtualenv's executable names
#vrenv2=virtualenv2
#hash virtualenv-2.7 2>/dev/null && vrenv2=virtualenv-2.7
#vrenv3=virtualenv3
#hash virtualenv-3.6 2>/dev/null && vrenv3=virtualenv-3.6
vrenv2=virtualenv
vrenv3=virtualenv
```
I did this, ran the script, and it worked. Both venvs are now installed and neovim pretty much fired up. Had to update some plugins, but eventually all seems well.

Looks like a nice neovim config so far 👍

**Comment by valh1996** [comment]
It works thank you :) ! But when i use nvim i have this interface... What is the problem ? I'm a noob with vim hahah
<img width="906" alt="capture d ecran 2018-01-27 a 00 58 44" src="https://user-images.githubusercontent.com/20521112/35465560-407950c0-02fd-11e8-8d3d-18192f495697.png">

**Comment by korlaxxalrok** [comment]
Wellll... :)

The rest is kind of up to you.

Initially, from your screenshot, it looks like some plug-in updates are happening, so that is probably one of the first times you've opened it up. Seems good, like things are working.

Vim/Neovim is a whole "thing", and there is potentially a lot to learn depending on how deep you want/need to go.

There is built-in help, so if you do `:h + Enter` you'll get some stuff. There are tons of Vim tutorials online around how to move around with the directional keys, how to edit text, etc. It is a new world to explore.

**Comment by rafi** [comment]
@korlaxxalrok @valh1996 what package manager did you use to install `virtualenv`? what OS are you using?

Do you have only one executable named `virtualenv`? what version?

**Comment by korlaxxalrok** [comment]
@rafi Howdy.

- OS: `macOS 10.13.3`
- I used `pip2` to install `virtualenv`. Well, I think I actually did the pip2/pip3 install process, but they appear to do the same thing once they stash the packages in their respective python directories, and you end up with basically the same thing, just called with a different python version (depending on which one was last).
- It appears that a script is placed here, again no matter which one is used: `/usr/local/bin/virtualenv`
- I have Python 2.7.14 and 3.6.4 installed via homebrew

**Comment by rafi** [comment]
@korlaxxalrok 👋  thanks for the details.
1. Can you list your python executable files? is it `python2` and `python3`?
1. Can you run Neovim and copy the output of `:checkhealth` here?

Thanks

**Comment by korlaxxalrok** [comment]
Looks like homebrew is nice enough to do this:
- Puts `python 2.7` at `/usr/local/opt/python/libexec/bin/python`.
- Puts `python 3.6` at `/usr/local/bin/python3.6`.
- `:checkhealth`(I'll keep it short with just the python only, everything else is "OK")
```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/Users/bgc/.cache/vim/venv/neovim2/bin/python"
  - INFO: Executable: /Users/bgc/.cache/vim/venv/neovim2/bin/python
  - WARNING: Unexpected Python version. This could lead to confusing error messages.
  - INFO: Python2 version: 3.6.4
  - INFO: python-neovim version: 0.2.0 (outdated; from ~/.cache/vim/venv/neovim2/lib/python3.6/site-packages/neovim)
  - WARNING: Latest python-neovim is NOT installed: 0.2.1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Users/bgc/.cache/vim/venv/neovim3/bin/python"
  - INFO: Executable: /Users/bgc/.cache/vim/venv/neovim3/bin/python
  - INFO: Python3 version: 3.6.4
  - INFO: python-neovim version: 0.2.0 (outdated; from ~/.cache/vim/venv/neovim3/lib/python3.6/site-packages/neovim)
  - WARNING: Latest python-neovim is NOT installed: 0.2.1
```

**Comment by rafi** [comment]
@korlaxxalrok @valh1996  I improved `venv.sh`, see 8005df90aed2f5a8ba258e693774c92fc682ddba
can you try it and report any issues?  Thanks 🙏

**Comment by korlaxxalrok** [comment]
@rafi 
Looks good 👍 !

I tired to do as fresh of an install as I could, and everything went smoothly. 

The Python provider checks look correct.
```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/Users/bgc/.cache/vim/venv/neovim2/bin/python"
  - INFO: Executable: /Users/bgc/.cache/vim/venv/neovim2/bin/python
  - INFO: Python2 version: 2.7.14
  - INFO: python-neovim version: 0.2.1
  - OK: Latest python-neovim is installed: 0.2.1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Users/bgc/.cache/vim/venv/neovim3/bin/python"
  - INFO: Executable: /Users/bgc/.cache/vim/venv/neovim3/bin/python
  - INFO: Python3 version: 3.6.4
  - INFO: python-neovim version: 0.2.1
  - OK: Latest python-neovim is installed: 0.2.1
```

**Comment by ttchin** [comment]
I installed vim-config in a ubuntu 16.04 docker container and met the same issue.

I fix this issue by:
```
apt-get install -y python3-venv
pip install virtualenv
```

**Comment by komali2** [comment]
I fixed this issue via:


`cp /home/calebrogers/.cache/vim/venv/neovim2/bin/pip /home/calebrogers/.cache/vim/venv/neovim3/bin/pip`

**Comment by rafi** [comment]
@ttchin thanks, added to README.md
