### ISSUE TITLE
CamelCaseMotion leads to unexpected behavior

### ISSUE THREAD

**Issue by subwindow** [rafi/vim-config#63]
When I use `w`, especially when using `cw`, it moves through special characters (including newlines). As a long time vim user, this is unexpected behavior and is extremely frustrating. It look me a long time to realize that vim-config had remapped the word navigation keys here https://github.com/rafi/vim-config/blob/master/config/plugins/all.vim#L304-L314 .

See also https://github.com/bkad/CamelCaseMotion/issues/18 . It's been identified as an issue, but the pull request to fix it was rejected for some unknown reason.

I had to delete those lines in all.vim order to get back my native vim word navigation. I cannot imagine why someone would want the behavior as exists in CamelCaseMotion. I propose that the bindings in all.vim be changed to `<leader>w`, etc, in order to preserve expected behavior.

**Comment by rafi** [comment]
Hi @subwindow, thanks for writing this up. I have to agree with you, it sure confuses and doesn't really add any real value. I'll remove it and hope I won't miss it :)
