### ISSUE TITLE
Spell Checking : Searching for .../spell/en.utf-8.add.spl

### ISSUE THREAD

**Issue by thecontinium** [rafi/vim-config#64]
Hi 

Great Config!

I have been using it for some time with neovim and noticed that on some files it was very slow to load.
After some investigation I found that it was a file type that was setting spell and in turn then searching for a spell file spell/en.utf-8.add under many directories many many times!

Resulting in:

```vim
not found in 'runtimepath': "spell/en.utf-8.add.spl"
E484: Can't open file /Users/thecontinium/.config/nvim/spell/en.utf-8.add.spl
```
Have you experienced this ?

In config/general.vim you setup spelling with:
```vim
set nospell spellfile=$VIMPATH/spell/en.utf-8.add
```
but never seem to create the `spell` directory or the file `en.utf-8.add`; where are they on your setup  ?

Help appreciated.

cheers

**Comment by thecontinium** [comment]
I made some more investigation and managed to get spelling working by:

1. creating a spell directory `~/.config/nvim/spell`
2. amended `~/.config/nvim/config/init.vim` so that `spellfile` plugin works  ( it uses `netrw` ) and spell files are downloaded ( not included with neovim ) when `set spell`  is used for the first time. What was your motivation to disable all of these; improve load speed ?

```vim
" Disable pre-bundled plugins
let g:loaded_getscript = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logiPat = 1
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
"let g:loaded_netrw = 1
"let g:loaded_netrwPlugin = 1
let g:loaded_netrwFileHandlers = 1
let g:loaded_netrwSettings = 1
let g:loaded_rrhelper = 1
let g:loaded_ruby_provider = 1
let g:loaded_shada_plugin = 1
"let g:loaded_spellfile_plugin  = 1
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_2html_plugin = 1
let g:loaded_vimball = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1
```

If you now add a word to your dictionary using `zg`, `en.utf-8.add` along with the associated `en.utf-8.add.spl` get created in `~/.config/nvim/spell`

**Comment by rafi** [comment]
Hi @thecontinium, thanks for the detailed report.
I have made the recommended changes, see d7b4187.

My motivation was indeed to improve performance, but it's not significant.
Hopefully first-time users would be able to download the spell files correctly from now on...

**Comment by thecontinium** [comment]
cool - thanks
