### ISSUE TITLE
Best way to disable plugins?

### ISSUE THREAD

**Issue by jeroenjanssens** [rafi/vim-config#66]
Thank you very much for creating this, @rafi! This config has many great plugins and sensible keybindings. There are, however, two plugins that I'm personally not a big fan of: `accelerated-jk` and `vim-cursorword`. What's the best way to disable these?

**Comment by zodiacg** [comment]
Make modification to plugins.yaml. Stash the changes before updating and apply it afterwards.
It's just a workaround. A modification of the whole structure might be needed to allow changes on plugins without causing problems when update.

**Comment by jeroenjanssens** [comment]
Thanks, that works for me.
