### ISSUE TITLE
iTerm2 Tab and Status Line Unrecognized Symbols

### ISSUE THREAD

**Issue by gruan** [rafi/vim-config#67]
The tab and status line have unknown characters, which is different from the preview you showed in the README.

<img width="1423" alt="screen shot 2018-02-12 at 3 42 51 pm" src="https://user-images.githubusercontent.com/4809816/36087122-8c5ca9fe-100b-11e8-89ff-85f4df06bd0e.png">

I'm on macOS High Sierra using iTerm2, $TERM=xterm-256color, font is Monaco. I also tried using Powerline's Terminus and Inconsolata but the problem still persisted.

Also just wanted to say that this config is really awesome!

**Comment by gruan** [comment]
Update: Resolved the issue in the bottom-right corner. Need to use a nerd font, found here https://github.com/ryanoasis/nerd-fonts.

Still having

**Comment by sdxy36** [comment]
> Update: Resolved the issue in the bottom-right corner. Need to use a nerd font, found here https://github.com/ryanoasis/nerd-fonts.

What specific nert font are you using?

**Comment by rafi** [comment]
Yes, see [nerdfonts.com](https://www.nerdfonts.com/) or change the characters in tabline and statusline.
