### ISSUE TITLE
Weird window display 

### ISSUE THREAD

**Issue by rhamaa** [rafi/vim-config#72]
I have a problem with "weird" display, i have to install powerline font + patching, but still have this problem
![screenshot_2018-03-25_12-27-59](https://user-images.githubusercontent.com/26088039/37872036-7f07ae4c-3028-11e8-931f-aa2643736150.png)

Vim version 7.4.1689

**Comment by thyeun** [comment]
@rhamaa same here, dont know what goes wrong.

**Comment by rafi** [comment]
What colorscheme are you using?

**Comment by rafi** [comment]
This looks like a `TERM` problems or a terminal that doesn't support those colors.
