### ISSUE TITLE
How do you repeat latest f,t,F or T?

### ISSUE THREAD

**Issue by ChandelierX** [rafi/vim-config#73]
I enjoy your neovim configurations. But there's one problem I fail to find an answer:
Since in the your default setting, `;` (semicolon) is used as a Local Leader in one of your plugins,
Then, how can I do what `;` and `,` did in original version (i.e., Repeat latest f, t, F or T [count] times.) without disabling your plugins?
Maybe there's a way to rebind `;` away from leader key?

**Comment by Chandelier309** [comment]
Well, I guess I find them in /config/init.vim. But I choose not change it cause I don't find appropriate alternative keys.
