### ISSUE TITLE
Neomake error in JSX Files

### ISSUE THREAD

**Issue by phatsk** [rafi/vim-config#75]
Whenever I write a file in my react project I get the following error:

```
Neomake error in: function neomake#Make[18]..<SNR>142_Make[123]..<SNR>142_handle_next_
Neomake: [8.-:-:1] Failed to start Neovim job: Executable not found: ['./node_modules/
.bin/eslint', '-f', 'compact', '/path/to/some.js'].
```

I can see that my `:pwd` is the folder where `node_modules` exists, and `node_modules/.bin/eslint` does exist. Running the command itself from the shell 
```
./node_modules/.bin/eslint -f compact /path/to/some.js
```

produces the expected output.

**Comment by Sacro** [comment]
It seems like it's not using :pwd, it's calling ./node_modules relative to the file you're trying to lint. No idea how to fix it however

**Comment by rafi** [comment]
Can you pull new changes? I've fixed it.
