### ISSUE TITLE
[OS X] yank doesn't work with visual mode

### ISSUE THREAD

**Issue by varunrau** [rafi/vim-config#76]
When I'm in visual mode, and press `y` vim copies that text, but with this config it seems to be a no-op. `p` will paste whatever is on my system's clipboard. Is that expected behavior? Deleting and pasting works the same as vanilla vim though.

Thanks for the great config!

**Comment by DancingQuanta** [comment]
I could not reproduce your issue. Did you modify your copy of vim-config?

**Comment by varunrau** [comment]
hmm interesting I did not. On a fresh install, I'm still seeing this issue.

**Comment by pacoyang** [comment]
I got the same issue and found the solution refer to [https://stackoverflow.com/questions/17561706/vim-yank-does-not-seem-to-work](url).
add `set clipboard^=unnamed,unnamedplus` to the file `config/local.vim` (If the `local.vim` file not exist create it). Hopes help.

**Comment by varunrau** [comment]
ah that makes sense. Based on that post, it looks like it should work on Linux because of [this](https://github.com/rafi/vim-config/blob/master/config/general.vim#L41), but not mac.

**Comment by pacoyang** [comment]
@varunrau yes, you are right, i didn't found that config. It should add unnamed to make clipboard work on mac.

**Comment by rafi** [comment]
So how did you solve your issue @varunrau ?

**Comment by varunrau** [comment]
On mac, the clipboard should be set like this: `set clipboard=unnamed` 

At the moment it's set [here](https://github.com/rafi/vim-config/blob/master/config/general.vim#L41), as `set clipboard& clipboard+=unnamedplus`

I'm happy to submit a PR for this.

**Comment by rafi** [comment]
@varunrau I'm on macOS and it works fine with `unnamedplus`.
Are you using Neovim? Can you take a look at `:h provider-clipboard` ?

**Comment by rafi** [comment]
@varunrau notice these lines: https://github.com/rafi/vim-config/blob/master/config/general.vim#L40-L53
They increase neovim's startup time and forces usage of pbcopy/pbpaste
