### ISSUE TITLE
Terminal wrong colors in OSX 10.13.4

### ISSUE THREAD

**Issue by klebermagno** [rafi/vim-config#77]
I use Terminal In my Mac with osx 10.13.4
the colors are totally wrong they don't show the highlighting but when I use iTerm vim-config work perfect.
<img width="932" alt="captura de tela 2018-04-23 as 17 27 33" src="https://user-images.githubusercontent.com/91983/39151457-a837e840-471b-11e8-933e-b8cbcf02eb55.png">

**Comment by rafi** [comment]
Are you using Vim or Neovim?

**Comment by klebermagno** [comment]
I'm using Neovim

**Comment by rafi** [comment]
You should check your `$TERM` value when you're in Terminal and iTerm2. Please report them back.

**Comment by klebermagno** [comment]
echo $TERM
xterm-256color
[~]━━ ━

**Comment by rafi** [comment]
Your terminal might not support 24bit colors, can you search for `termguicolors` in config and disable it?
