### ISSUE TITLE
bottom left corner not appear correctly

### ISSUE THREAD

**Issue by thyeun** [rafi/vim-config#79]
Sorry, i'm not sure how to edit or change or recorrect the appear of the bottom left corner.

As you can see, it should be appear ```N``` mode but it is now appear every mode with ```#1```

![screenshot_2018-05-31_00-52-01](https://user-images.githubusercontent.com/1939446/40735326-809db886-646d-11e8-92ab-c2a97ab3bb76.jpg)

Possible to let me know which file to make a modify, so that it will appear correctly

**Comment by rafi** [comment]
It shows the buffer number.
If you want to see the mode, you can use `set showmode` in `config/local.vim` (Create it if it doesn't exist).
You can also change the style of it in `themes/rafi-2017.vim`.

**Comment by thyeun** [comment]
thanks, i been resolve it myself.
