### ISSUE TITLE
vim-config on MS Windows

### ISSUE THREAD

**Issue by kraxli** [rafi/vim-config#80]
is there a way to use vim-config on MS Windows? I just cannot get it to work :-( 

Does somebody has some experiences/tips to share?

Thx
Dave

**Comment by DancingQuanta** [comment]
I have it working on Windows 10 with Cygwin and WSL. What Windows environment do you have?
Are you using vim8 or neovim? I used both.

For Neovim in WSL I installed python2 and python3 and used virtualenvs for neovim.
For Vim8 in Cygwin, I used cygwin's vim.

**Comment by kraxli** [comment]
Thanks for the reply! In my old job I also had WSL available and it was working fine. This time I finally solved it by mainly "replacing" dein with plug and fixed dependencies. So it is working on "pure" Windows.
