### ISSUE TITLE
Error when opening nvim

### ISSUE THREAD

**Issue by benedikt-bartscher** [rafi/vim-config#86]
I always get this error when i open nvim:
Fehler beim Ausführen von "/home/benedikt/.config/nvim/config/theme.vim":
Zeile   37:
E684: List-Index außerhalb des zulässigen Bereichs: 0
E15: ungültiger Ausdruck: filereadable(s:cache) ? readfile(s:cache)[0] : 'hybrid'
Betätigen Sie die EINGABETASTE oder geben Sie einen Befehl ein

**Comment by rafi** [comment]
Could you give me the output of `cat ~/.cache/vim/theme.txt` ?
