### ISSUE TITLE
How can I make the denite search less fuzzy?

### ISSUE THREAD

**Issue by nastynaz** [rafi/vim-config#89]
Currently the search matcher in files is very fuzzy. Is there any way to change that?

**Comment by rafi** [comment]
You can add in [config/plugins/denite.vim](https://github.com/rafi/vim-config/blob/master/config/plugins/denite.vim) the following:

```vim
call denite#custom#source(
	\ 'buffer,file_mru,file_old,file/rec,grep,mpc,line',
	\ 'matchers', ['matcher/substring'])
```

See a full list of Denite matchers with `:h denite-filters`
