### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by tony-yin** [rafi/vim-config#90]
make error:
Vim(let):E117: Unknown function: neomake#statusline#LoclistCounts

make on mac will appear this error msg, but it will be normal on linux

**Comment by rafi** [comment]
Do you have any local changes you've made in nvim config?

**Comment by tony-yin** [comment]
Problem was solved, because neomake did not load which  airline need.  I mamully installed or load neomake plugin， this problem went away.

This problem often occured because of lazy load.  Can you check it and revise to automatic? thanks

And always stuck in this setp:
![image](https://user-images.githubusercontent.com/18906553/47980525-0df34b80-e103-11e8-9fe8-72f83742a144.png)
