### ISSUE TITLE
nvim display differently between bash and tmux

### ISSUE THREAD

**Issue by tony-yin** [rafi/vim-config#94]
```
env: 
os: linux-centos7
ssh: xshell/putty
```
When I use the config , I find nvim display differently between bash and tmux. It display normally in tmux, but display error in bash.

bash snapshot:
![image](https://user-images.githubusercontent.com/18906553/50210857-2ae19680-03b2-11e9-91d1-39e154879145.png)

tmux snapshot:
![image](https://user-images.githubusercontent.com/18906553/50210933-56648100-03b2-11e9-9574-9332eb66a764.png)

This also appears on osx between default terminal and iterm2. Default terminal displays error like bash, and iterm2 displays normally like tmux.

I have tried on powerline and powerline fonts, but it didn't make sense. Can you help find reason? thanks!!!

**Comment by rafi** [comment]
Sounds like a problem with your `TERM` environment variable... there's a lot of people asking about it in the [internet](https://github.com/neovim/neovim/search?q=color+issue+TERM&type=Issues)..

Try setting `TERM` to `xterm-256color`

**Comment by tony-yin** [comment]
`TERM` is setted `xterm-256color`, not concerned with it

**Comment by tony-yin** [comment]
I doubt if problem with terminal support for true color

**Comment by tony-yin** [comment]
hahah, interesting. I have tried many ssh clients like putty, kitty, terminus. And I find nvim in terminus is normal display. But why putty and kitty still display error ? I saw they support true color:https://gist.github.com/XVilka/8346728#now-supporting-truecolour

**Comment by rafi** [comment]
Try to disable `termguicolors` in [`config/theme.vim#L10`](https://github.com/rafi/vim-config/blob/master/config/theme.vim#L10) and maybe `t_Co` above it.
