### ISSUE TITLE
Could not find a version that satisfies the requirement pynvim (from versions: ) No matching distribution found for pynvim

### ISSUE THREAD

**Issue by JTL1992** [rafi/vim-config#95]
env: mac 10.14
when i run ./venv.sh

Could not fetch URL https://pypi.python.org/simple/pynvim/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement pynvim (from versions: )
No matching distribution found for pynvim

**Comment by rafi** [comment]
@JTL1992 it looks like you have a problem with installing pypi packages with pip. Try to [search](https://www.google.com/search?q=pypi+TLSV1_ALERT_PROTOCOL_VERSION) the web for your error..
