### ISSUE TITLE
Cursor is almost invisible in tabline

### ISSUE THREAD

**Issue by maccyber** [rafi/vim-config#96]
My cursor is almost invisible at the tabline.

Any way to change the color easily? 

![tabline_cursor_color](https://user-images.githubusercontent.com/701351/51927678-641b1680-23f4-11e9-99d1-784db296a347.png)

Thanks for an awesome config, btw.

**Comment by rafi** [comment]
What terminal are you using? It's usually there where you can change this kind of setting.

**Comment by maccyber** [comment]
Ah, thanks for the hint.

`termite v14` - will look into the terminal-config.

**Comment by maccyber** [comment]
Sat the cursor to a solid color with
```
[colors]
cursor = #dcdccc
```

That did the trick.
