### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by taigacute** [rafi/vim-config#97]
Hi @rafi ！ i have use your config，when  i edit go file, the syntax is very interesting, it apper on my error line and prompt me `undefined daf` how to do this? what's plugins? thanks
![webwxgetmsgimg](https://user-images.githubusercontent.com/41671631/53559815-fb0af800-3b85-11e9-9c99-10aa665c6102.jpg)

**Comment by rafi** [comment]
hi @taigacute, the plugin that does this is [Neomake](https://github.com/neomake/neomake). It's a powerful asynchronous linting framework for Neovim/Vim. The annotation is all thanks to Neovim's "virtualtext" feature.

**Comment by taigacute** [comment]
thanks very much，What configuration and plugins are required for this feature? My own configuration uses coc, can I work with neomake?

**Comment by rafi** [comment]
I'm not familiar with 'coc'. Search or ask about the 'virtualtext' feature in coc.
